In [ ]:
..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/

---   
 <img align="left" width="75" height="75"  src="https://upload.wikimedia.org/wikipedia/en/c/c8/University_of_the_Punjab_logo.png"> 

<h1 align="center">Department of Data Science</h1>
<h1 align="center">Course: Tools and Techniques for Data Science</h1>

---
<h3><div align="right">Instructor: Muhammad Arif Butt, Ph.D.</div></h3>    

<h1 align="center">Lecture 3.11 (Pandas-03)</h1>

<img align="right" width="400" height="400"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/pandas-apps.png"  >

## _Overview of Pandas Dataframe Data Structure_

## Learning agenda of this notebook
1. Anatomy of a Dataframe
2. Creating Dataframe
    - An empty dataframe
    - Two-Dimensional NumPy Array
    - Dictionary of Python Lists
    - Dictionary of Panda Series
2. Attributes of a Dataframe
3. Bonus

In [1]:
import pandas as pd
pd.__version__, pd.__path__

('2.0.3', ['C:\\Users\\FashN\\anaconda3\\Lib\\site-packages\\pandas'])

<img align="right" width="500" height="500"  src="images/pandas00.png"  >

## 1. Creating a Dataframe
<br><br>
>**A Pandas Dataframe is a two-dimensional labeled data structure (like SQL table) with heterogeneously typed columns, having both a row and a column index.**

<br><br><br><br>

**```pd.DataFrame(data=None, index=None, columns=None, dtype=None)```**
- Where,
   - `data`: It can be a 2-D NumPy Array, a Dictionary of Python Lists, or a Dictionary of Panda Series (You can also create a dataframe from a file in CSV, Excel, JSON, HTML format or may be from a database table as well).
   - `index`: These are the row indices. Will default to RangeIndex (0, 1, 2, ..., n), if index argument is not passed and no indexing information is part of input data.
   - `columns`: These are the column indices or labels. Will default to RangeIndex (0, 1, 2, ..., n), if index argument is not passed and no indexing information is part of input data.
   - `dtype`: Data type to force. Only a single dtype is allowed. If None, infer.

### a. Creating an Empty Dataframe

In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame()
new = pd.DataFrame()

print(f'df = {df}\nnew = {new}')


df = Empty DataFrame
Columns: []
Index: []
new = Empty DataFrame
Columns: []
Index: []


### b. Creating a Dataframe from a 2-D NumPy Array

In [3]:
arr = np.random.randint(10,100, size=(6,5))

df = pd.DataFrame(data=arr)
print(f'Numpy Array:\n{arr}\n\ndf = {df}')

Numpy Array:
[[69 34 70 88 47]
 [27 18 26 71 86]
 [75 36 63 20 51]
 [29 70 59 99 19]
 [77 40 48 42 52]
 [62 89 67 89 13]]

df =     0   1   2   3   4
0  69  34  70  88  47
1  27  18  26  71  86
2  75  36  63  20  51
3  29  70  59  99  19
4  77  40  48  42  52
5  62  89  67  89  13


- Note that both the row indices and the column labels/indices are implicitly set to numerical values from 0 to n-1, since neither of the two is provided while creating the dataframe object. They are also not considered as part of data in the dataframe.
- In majority of the cases the row label is left as default, i.e., 0,1,2,3.... However, the column labels are changed from 0,1,2,3,... to some meaningful values.

In [7]:
# Let us name the column labels of our choice, while creating it
col_labels = ['Col1', 'Col2', 'Col3', 'Col4', 'Col5']
# Let us name the row labels of our choice, while creating it
# df = pd.DataFrame(data=arr, index=['Row0', 'Row1', 'Row2', 'Row3', 'Row4', 'Row5'])

rows=['Row0', 'Row1', 'Row2', 'Row3', 'Row4', 'Row5']


df = pd.DataFrame(data=arr, columns=col_labels, index=rows)
df

Col1  Col2  Col3  Col4  Col5
Row0    69    34    70    88    47
Row1    27    18    26    71    86
Row2    75    36    63    20    51
Row3    29    70    59    99    19
Row4    77    40    48    42    52
Row5    62    89    67    89    13

### c. Creating a Dataframe from a Dictionary of Python Lists
- You can create a dataframe object from a dictionary of Python Lists 
    - The dictionary `Keys` become the column names, and 
    - The dictionary `Values` are lists/arrays containing data for the respective columns.

In [11]:
people = {
    "name" : ["Godwin", "Abimbola", "Joy", "Blessing", "Gloria", "Simon"],
    "age" : [52, 51, 26, 22, 18, 17],
    "address": ["U.K.", "U.K.", "Nigeria", "Canada", "China", "Korea"],
    "cell" : ["321-123", "320-431", "321-478", "324-446", "321-967", "320-678"],
    "bg": ["A+", "A-", "A+", "A-", "A-", "A+"]
}
people

# Pass this Dictionary of Python Lists to pd.Dataframe()
df = pd.DataFrame(data=people)
print(f'Dictionary:\n{people}\n\ndf = \n{df}')
df

Dictionary:
{'name': ['Godwin', 'Abimbola', 'Joy', 'Blessing', 'Gloria', 'Simon'], 'age': [52, 51, 26, 22, 18, 17], 'address': ['U.K.', 'U.K.', 'Nigeria', 'Canada', 'China', 'Korea'], 'cell': ['321-123', '320-431', '321-478', '324-446', '321-967', '320-678'], 'bg': ['A+', 'A-', 'A+', 'A-', 'A-', 'A+']}

df = 
       name  age  address     cell  bg
0    Godwin   52     U.K.  321-123  A+
1  Abimbola   51     U.K.  320-431  A-
2       Joy   26  Nigeria  321-478  A+
3  Blessing   22   Canada  324-446  A-
4    Gloria   18    China  321-967  A-
5     Simon   17    Korea  320-678  A+


name  age  address     cell  bg
0    Godwin   52     U.K.  321-123  A+
1  Abimbola   51     U.K.  320-431  A-
2       Joy   26  Nigeria  321-478  A+
3  Blessing   22   Canada  324-446  A-
4    Gloria   18    China  321-967  A-
5     Simon   17    Korea  320-678  A+

In [12]:
# Let us change the row labels of above dataframe
row_labels = ['MS01', 'MS02', 'MS03', 'MS04', 'MS05', 'MS06']
df.index = row_labels
df

name  age  address     cell  bg
MS01    Godwin   52     U.K.  321-123  A+
MS02  Abimbola   51     U.K.  320-431  A-
MS03       Joy   26  Nigeria  321-478  A+
MS04  Blessing   22   Canada  324-446  A-
MS05    Gloria   18    China  321-967  A-
MS06     Simon   17    Korea  320-678  A+

### d. Creating a Dataframe from Dictionary of Panda Series
One can think of a dataframe as a dictionary of Panda Series: 
- `Keys` are column names, and 
- `Values` are Series object for the respective columns.

In [13]:
dict = {
    "name": pd.Series(['Spiderman', 'Nova', 'Powerman', 'Iron Fist', 'White Tiger']),
    "age": pd.Series([18, 17, 16, 19, 18]),
    "address":pd.Series(['New York', 'Chicago', 'Brooklyn', 'Idaho', 'Seattle'])
}

df = pd.DataFrame(data=dict)
df

name  age   address
0    Spiderman   18  New York
1         Nova   17   Chicago
2     Powerman   16  Brooklyn
3    Iron Fist   19     Idaho
4  White Tiger   18   Seattle

>Note from the above output, that every series object becomes the data of the appropriate column. Moreover, the keys of the dictionary become the column labels.

In [14]:
dict = {
    "name": pd.Series(['Spiderman', 'Nova', 'Powerman', 'Iron Fist', 'White Tiger'], index=['a', 'b', 'c', 'd', 'e']),
    "age": pd.Series([18, 17, 16, 19, 18], index=['a', 'b', 'c', 'd', 'e']),
    "address":pd.Series(['New York', 'Chicago', 'Brooklyn', 'Idaho', 'Seattle'], index=['a', 'b', 'c', 'd', 'e'])
}

df = pd.DataFrame(data=dict)
df

name  age   address
a    Spiderman   18  New York
b         Nova   17   Chicago
c     Powerman   16  Brooklyn
d    Iron Fist   19     Idaho
e  White Tiger   18   Seattle

In [15]:
dict = {
    "name": pd.Series(['Spiderman', 'Nova', 'Powerman', 'Iron Fist', 'White Tiger'], index=['a', 'b', 'c', 'd', 'white']),
    "age": pd.Series([18, 17, 16, 19, 18], index=['a', 'special', 'c', 'd', 'e']),
    "address":pd.Series(['New York', 'Chicago', 'Brooklyn', 'Idaho', 'Seattle'], index=['a', 'b', 'c', 'd', 'e'])
}

df = pd.DataFrame(data=dict)
df

name   age   address
a          Spiderman  18.0  New York
b               Nova   NaN   Chicago
c           Powerman  16.0  Brooklyn
d          Iron Fist  19.0     Idaho
e                NaN  18.0   Seattle
special          NaN  17.0       NaN
white    White Tiger   NaN       NaN

In [16]:
df.head(-3)

name   age   address
a  Spiderman  18.0  New York
b       Nova   NaN   Chicago
c   Powerman  16.0  Brooklyn
d  Iron Fist  19.0     Idaho

In [17]:
df.tail(-4)

name   age  address
e                NaN  18.0  Seattle
special          NaN  17.0      NaN
white    White Tiger   NaN      NaN

>- In the above code and its output, note that first series object has four data values and four corresponding indices. Similarly, second series object has four data values (with one `np.nan` value) and four corresponding indices, which are a bit different from the first series object. Third series has three data values (with one empty string) and three indices.
>- Note the resulting Dataframe has six rows and three columns.
    - For index 'a' we have value in all the three series objects or columns.
    - For index 'b' we have a value in first series object, and NaN for the second and third column, since the second and third series object has no value corresponding to row index 'b.

## 3. Attributes of Pandas Dataframe
- Like Series, we can access properties/attributes of a dataframe by using dot `.` notation

In [33]:
people = {
    "name": ['Spiderman', 'Nova', 'Powerman', 'Iron Fist', 'White Tiger'],
    "age": [18, 17, 16, 19, 18],
    "address":['New York', 'Chicago', 'Brooklyn', 'Idaho', 'Seattle']
}

df = pd.DataFrame(data=people, index=['MS01', 'MS02', 'MS03', 'MS04', 'MS05'])
df

name  age   address
MS01    Spiderman   18  New York
MS02         Nova   17   Chicago
MS03     Powerman   16  Brooklyn
MS04    Iron Fist   19     Idaho
MS05  White Tiger   18   Seattle

In [37]:
# `shape` attribute of a dataframe object return a two value tuple containing rows and columns
# Note the rows count does not include the column labels and column count does not include the row index
# `ndim` attribute of a dataframe object returns number of dimensions (which is always 2)
# `size` attribute of a dataframe object returns the number of elements in the underlying data
# `index` attribute of a dataframe object return the list of row indices and its datatype# `columns` attribute of a dataframe object return the list of column labels and its datatype
#This attribute is used to fetch both index and column names.
# `values` attribute of a dataframe object returns a NumPy 2-D having all the values in the DataFrame, 
# without the row indices and column labels

print(f'shape = {df.shape}\n\ndf.ndim = {df.ndim}\n\ndf = {df.size}\n\ndf.index = {df.index}\n\ndf.columns = {df.columns}\n\ndf.axes = {df.axes}\n\ndf.values = {df.values}\n\ndf.empty = {df.empty}\n\ndf.dtypes = {df.dtypes}\n\ndf.count = {df.count}')

shape = (5, 3)

df.ndim = 2

df = 15

df.index = Index(['MS01', 'MS02', 'MS03', 'MS04', 'MS05'], dtype='object')

df.columns = Index(['name', 'age', 'address'], dtype='object')

df.axes = [Index(['MS01', 'MS02', 'MS03', 'MS04', 'MS05'], dtype='object'), Index(['name', 'age', 'address'], dtype='object')]

df.values = [['Spiderman' 18 'New York']
 ['Nova' 17 'Chicago']
 ['Powerman' 16 'Brooklyn']
 ['Iron Fist' 19 'Idaho']
 ['White Tiger' 18 'Seattle']]

df.empty = False

df.dtypes = name       object
age         int64
address    object
dtype: object

df.count = <bound method DataFrame.count of              name  age   address
MS01    Spiderman   18  New York
MS02         Nova   17   Chicago
MS03     Powerman   16  Brooklyn
MS04    Iron Fist   19     Idaho
MS05  White Tiger   18   Seattle>


In [ ]:
df