..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/

# _Basic Operations on NumPy Arrays.ipynb_

<img align="center" width="500" height="500"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/basicopsonnumpy.png" > 

# Learning agenda of this notebook
- Operations on numPy arrays are done element-wise. This means that you don't explicitly have to write for-loops in order to do these operations!
- A universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays. You can think of them as fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results.


<img align="left" width="450" height="400"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/ufuncunary.png" > 
<img align="right" width="485" height="500"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/ufuncbinary.png" > 

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

1. Scalar Math
    - On 1-D Arrays
    - On 2-D Arrays
2. Arithmetic operations
    - On 1-D Arrays
    - On 2-D Arrays
3. More Mathematical Operations
    - On 1-D Arrays
    - On 2-D Arrays
4. Aggregate Functions
    - On 1-D Arrays
    - On 2-D Arrays
5. Comparing NumPy Arrays
    - On 1-D Arrays
    - On 2-D Arrays
6. Bonus: Searching 1-D and 2-D NumPy Arrays using `numpy.where()`

In [6]:
import numpy as np
print(np.__version__)
print(np.__path__)

1.24.3
['C:\\Users\\FashN\\anaconda3\\Lib\\site-packages\\numpy']


## 1. Scalar Math

### a. Scalar Math on 1-D Arrays

In [11]:
# Create a 1-D array having 4 random integers from 1 to 9
arr = np.random.randint(1,10, size=4)
print(f"1-D array:\n {arr}")

1-D array:
 [2 3 9 1]


In [14]:
# After the operation a new `ndarray` is returned
print(f"arr = {arr}\nadding 2 to the numpy array {arr+2}")

arr = [2 3 9 1]
adding 2 to the numpy array [ 4  5 11  3]


In [15]:
print(f"arr = {arr}\nsubtracting 1 from the numpy array {arr-1}")

arr = [2 3 9 1]
subtracting 1 from the numpy array [1 2 8 0]


In [16]:
print(f"arr = {arr}\nmultiplying the numpy array by 3{arr*3}")

arr = [2 3 9 1]
multiplying the numpy array by 3[ 6  9 27  3]


In [17]:
print(f"arr = {arr}\nmultiplying the numpy array by 2{arr/2}")

arr = [2 3 9 1]
multiplying the numpy array by 2[1.  1.5 4.5 0.5]


In [19]:
print(f"arr = {arr}\nmod 2 of the numpy array {arr%2}")

arr = [2 3 9 1]
mod 2 of the numpy array [0 1 1 1]


In [20]:
arr2 = arr + 5
print(id(arr), id(arr2))

2098984007216 2098984006448


### b. Scalar Math on 2-D Arrays


In [24]:
# Create a 2x2 matrix with random integers  between 1 to 9
arr = np.random.randint(1,10, size=(2,2))
print(f"Matrix = {arr}")

Array = [[1 3]
 [5 8]]


In [26]:
print(f"Matrix = \n{arr}\nadding 2 to the numpy array \n{arr+2}")

Matrix = 
[[1 3]
 [5 8]]
adding 2 to the numpy array 
[[ 3  5]
 [ 7 10]]


In [27]:
print(f"Matrix = \n{arr}\nsubtracting 1 from the numpy array \n{arr-1}")

Matrix = 
[[1 3]
 [5 8]]
subtracting 1 from the numpy array 
[[0 2]
 [4 7]]


In [28]:
print(f"Matrix = \n{arr}\nmultiplying the numpy array by 3 \n{arr*3}")

Matrix = 
[[1 3]
 [5 8]]
multiplying the numpy array by 3 
[[ 3  9]
 [15 24]]


In [29]:
print(f"Matrix = \n{arr}\ndividing the numpy array by 2 \n{arr/2}")

Matrix = 
[[1 3]
 [5 8]]
dividing the numpy array by 3 
[[0.5 1.5]
 [2.5 4. ]]


In [30]:
print(f"arr = \n{arr}\nmod 2 of the numpy array \n{arr%2}")

arr = 
[[1 3]
 [5 8]]
mod 2 of the numpy array 
[[1 1]
 [1 0]]


## 2. Arithmetic Operations


### a. Arithmetic Operations on 1-D Arrays


In [33]:
arr1 = np.random.randint(1,10, size=4)
arr2 = np.random.randint(11,20, size=4)
print(f'Array1:\n{arr1}\nArray2:\n{arr2}')

Array1:
[4 7 8 7]
Array2:
[13 11 19 18]


In [35]:
# After the operation a new `ndarray` is returned
print(f'Addition of both arrays:\n{arr1+arr2}')

Addition of both arrays:
[17 18 27 25]


In [37]:
print(f'Subtraction of array1 from array2:\n{arr2-arr1}')

Subtraction of array1 from array2:
[ 9  4 11 11]


In [38]:
print(f'Division of array1 by array2:\n{arr2/arr1}')

Division of array1 by array2:
[3.25       1.57142857 2.375      2.57142857]


In [56]:
print(f'Multiplication of array1 by array2:\n{arr2*arr1}')

Multiplication of array1 by array2:
[[80 39]
 [66 48]]


### b. Arithmetic Operations on 2-D Arrays

In [50]:
# Create a 2x2 matrix with random integers  between 1 to 9
arr1 = np.random.randint(1, 10,size=(2,2))
arr2 = np.random.randint(11, 20,size=(2,2))

print(f'Array1:\n{arr1}\nArray2:\n{arr2}')

Array1:
[[5 3]
 [6 3]]
Array2:
[[16 13]
 [11 16]]


In [51]:
print(f'Addition of both arrays:\n{arr1+arr2}')

Addition of both arrays:
[[21 16]
 [17 19]]


In [52]:
print(f'Subtraction of array1 from array2:\n{arr2-arr1}')

Subtraction of array1 from array2:
[[11 10]
 [ 5 13]]


In [55]:
print(f'Multiplication of array1 by array2:\n{arr2*arr1}')

Multiplication of array1 by array2:
[[80 39]
 [66 48]]


In [57]:
print(f'Division of array1 by array2:\n{arr2/arr1}')

Division of array1 by array2:
[[3.2        4.33333333]
 [1.83333333 5.33333333]]


## 3. More Mathematical Operations

### a. Mathematical Operations on 1-D Array

In [59]:
# Creating 1-D array of 5 elements of random floats between 1 and 10
arr = np.random.rand(5)*10
print(f"Array:\n{arr}")

Array:
[8.04889372 7.5862381  9.42275788 9.26690927 7.66739785]


In [60]:
# After the operation a new `ndarray` is returned, which is a copy of the original array with the operation performed
print(f"np.abs = {np.abs(arr)}")

np.abs = [8.04889372 7.5862381  9.42275788 9.26690927 7.66739785]


In [61]:
print(f"np.square = {np.square(arr)}")

np.square = [64.78469008 57.55100857 88.78836605 85.8756074  58.78898986]


In [62]:
print(f"np.sqrt = {np.sqrt(arr)}")

np.sqrt = [2.83705723 2.75431264 3.0696511  3.04415986 2.76900665]


In [63]:
print(f"np.cbrt = {np.cbrt(arr)}")

np.cbrt = [2.0040662  1.96490771 2.11215609 2.10044656 1.97188992]


In [64]:
print(f"np.log = {np.log(arr)}")

np.log = [2.08553466 2.02633583 2.24312781 2.22644991 2.0369773 ]


In [65]:
print(f"np.log2 = {np.log2(arr)}")

np.log2 = [3.00879051 2.92338465 3.23614937 3.21208825 2.93873704]


In [66]:
print(f"np.log10 = {np.log10(arr)}")

np.log10 = [0.90573619 0.88002647 0.97417803 0.96693491 0.884648  ]


In [67]:
print(f"np.isnan = {np.isnan(arr)}")

np.isnan = [False False False False False]


In [68]:
print(f"np.floor = {np.ceil(arr)}")

np.floor = [ 9.  8. 10. 10.  8.]


In [69]:
print(f"np.cumsum = {np.cumsum(arr)}")

np.cumsum = [ 8.04889372 15.63513182 25.0578897  34.32479897 41.99219682]


In [70]:
print(f"np.floor = {np.floor(arr)}")

np.floor = [8. 7. 9. 9. 7.]


### b. Mathematical Operations on 2-D Array


In [71]:
# Create a 2x2 matrix with random integers  between 1 to 9
matrix = np.random.randint(1,20, size=(2,2))
print(f'Matrix:\n{matrix}')

Matrix:
[[4 2]
 [4 3]]


In [72]:
# After the operation a new `ndarray` is returned, which is a copy of the original array with the operation performed
print("np.square(matrix) = \n", np.square(matrix))
print("np.sqrt(matrix) = \n", np.sqrt(matrix))
print("np.log2(matrix) = \n", np.log2(matrix))
print("np.isnan(matrix) = \n", np.isnan(matrix))
print("np.ceil(matrix) = \n", np.ceil(matrix))
print("np.floor(matrix) = \n", np.floor(matrix))
print("np.cumsum(matrix) = \n", np.cumsum(matrix))

np.square(matrix) = 
 [[16  4]
 [16  9]]
np.sqrt(matrix) = 
 [[2.         1.41421356]
 [2.         1.73205081]]
np.log2(matrix) = 
 [[2.        1.       ]
 [2.        1.5849625]]
np.isnan(matrix) = 
 [[False False]
 [False False]]
np.ceil(matrix) = 
 [[4. 2.]
 [4. 3.]]
np.floor(matrix) = 
 [[4. 2.]
 [4. 3.]]
np.cumsum(matrix) = 
 [ 4  6 10 13]


## 4. Aggregate Functions


### a. Aggregate Functions on 1-D Arrays


In [73]:
arr = np.random.randint(3,15, size=5)
print(f'Array:\n{arr}')

Array:
[ 5 10 10 14 11]


In [74]:
# After the operation a new `ndarray` is returned, which is a copy of the original array with the operation performed
print(f"np.min = {np.min(arr)}")

np.min = 5


In [75]:
print(f"np.max = {np.max(arr)}")

np.max = 14


In [76]:
print(f"np.sum = {np.sum(arr)}")

np.sum = 50


In [77]:
print(f"np.prod = {np.prod(arr)}")

np.prod = 77000


In [78]:
#Arithmetic mean is the sum of elements along an axis divided by the number of elements. 
print(f"np.mean = {np.mean(arr)}")

np.mean = 10.0


In [81]:
# The np.average() function computes the weighted average, by multiplying of each array element by its weight
# The np.average() is same as np.mean(), when weight is not specified
print(f"np.average = {np.average(arr)}")

wghs = np.array([1,2,3,4,5])

print(f"np.average = {np.average(arr, weights = wghs)}")


np.average = 10.0
np.average = 11.066666666666666


In [84]:
arr = np.random.randint(1, 100, size=10)
print(f'arr:\n{arr}')

# Median is the value separating the higher half of a data sample from the lower half.
print(f'\nnp.median = {np.median(arr)}')

arr:
[94 81 89 42 93 73 29 78 56 98]

np.median = 79.5


In [87]:
#  Percentile is the value below which a given percentage of observations in a group of observations fall.
# 50th percentile is the score at or below which 50% of the scores in

print(f'np.percentile 50% {np.percentile(arr,50)}') #same as median value
print(f'np.percentile 0% {np.percentile(arr,0)}') #lowest value
print(f'np.percentile 100% {np.percentile(arr,100)}') #highest value

np.percentile 50% 79.5
np.percentile 0% 29.0
np.percentile 100% 98.0


In [89]:
# The variance measures the average degree to which each point differs from the mean
# Variance is calculated as the average of squared deviations from mean

print(f'np.var = {np.var(arr)}')

#  Standard deviation checks how spread out a group of numbers is from the mean
# It is the square root of variance: sqrt(mean((x - x.mean())**2))
print(f'np.std = {np.std(arr)}')

np.var = 499.60999999999996
np.std = 22.35195740869242


### b. Aggregate Functions on 2-D Arrays


In [92]:
# Create a 3x3 (2-D array) initialized with random integers from 1 to 9
matrix = np.random.randint(1,5, size=(3,3))
print(f'Matrix:\n{matrix}')

print(f'np.sum of matrix at axis=0:\n{np.sum(matrix,axis=0)}')

print(f'np.sum of matrix at axis=1:\n{np.sum(matrix,axis=1)}')

Matrix:
[[4 1 3]
 [1 1 2]
 [4 4 1]]
np.sum of matrix at axis=0:
[9 6 6]
np.sum of matrix at axis=1:
[8 4 9]


In [93]:
# Create a 3x3 (2-D array) initialized with random integers from 1 to 9
matrix = np.random.randint(1,10,size=(3,3))
print(f'Matrix:\n{matrix}')

print(f'np.min of matrix at axis=0:\n{np.min(matrix,axis=0)}')

print(f'np.max of matrix at axis=1:\n{np.max(matrix,axis=1)}')

Matrix:
[[5 3 4]
 [2 6 4]
 [1 4 2]]
np.min of matrix at axis=0:
[1 3 2]
np.max of matrix at axis=1:
[5 6 4]


In [94]:
# Create a 3x3 (2-D array) initialized with random integers from 1 to 9
matrix = np.random.randint(1,10,size=(4,4))
print(f'Matrix:\n{matrix}')

print(f'np.mean of matrix at axis=0:\n{np.mean(matrix,axis=0)}')

print(f'np.mean of matrix at axis=1:\n{np.mean(matrix,axis=1)}')

Matrix:
[[7 3 7 6]
 [3 8 8 7]
 [9 5 9 1]
 [5 5 1 4]]
np.mean of matrix at axis=0:
[6.   5.25 6.25 4.5 ]
np.mean of matrix at axis=1:
[5.75 6.5  6.   3.75]


In [95]:
# Create a 3x3 (2-D array) initialized with random integers from 1 to 9
matrix = np.random.randint(1,10,size=(4,4))
print(f'Matrix:\n{matrix}')

print(f'np.median of matrix at axis=0:\n{np.median(matrix,axis=0)}')

print(f'np.median of matrix at axis=1:\n{np.median(matrix,axis=1)}')

Matrix:
[[4 9 1 1]
 [9 4 5 6]
 [1 4 9 4]
 [2 7 6 9]]
np.median of matrix at axis=0:
[3.  5.5 5.5 5. ]
np.median of matrix at axis=1:
[2.5 5.5 4.  6.5]


Please do practice calculating the percentile, variance and standard deviation along different axis of a 2-D array

## 5. Comparing NumPy Arrays

### a. Comparing NumPy 1-D Arrays
- Returns a Boolean numpy array containing True/False after doing element wise comparison

In [104]:
# Create two 1-D arrays each having 4 random integers from 1 to 9
arr1 = np.random.randint(1,10, size=5)
arr2 = np.random.randint(1,10, size=5)

print(f'arr1:\n{arr1}')
print(f'arr2:\n{arr2}')

print(f'\nnp.equal(if arr1 == arr2)\n{arr1==arr2}')
print(f'\nnp.not_equal(if arr1 != arr2)\n{arr1!=arr2}')

print(f'\nnp.greater(if arr1 > arr2)\n{arr1>arr2}')
print(f'\nnp.greater_equal(if arr1 < arr2)\n{arr1<arr2}')



arr1:
[4 9 2 3 1]
arr2:
[6 8 8 9 2]

np.equal(if arr1 == arr2)
[False False False False False]

np.not_equal(if arr1 != arr2)
[ True  True  True  True  True]

np.greater(if arr1 > arr2)
[False  True False False False]

np.greater_equal(if arr1 < arr2)
[ True False  True  True  True]


### b. Comparing NumPy 2-D Arrays

In [107]:
matrix1 = np.random.randint(1,10, size=5)
matrix2 = np.random.randint(1,10, size=5)

print(f'matrix1:\n{matrix1}')
print(f'matrix2:\n{matrix2}')

print(f'\nnp.equal(if matrix1 == matrix2)\n{matrix1==arr2}')
print(f'\nnp.not_equal(if matrix1 != matrix2)\n{matrix1!=matrix2}')

print(f'\nnp.greater(if matrix1 > matrix2)\n{matrix1>matrix2}')
print(f'\nnp.greater_equal(if matrix1 < matrix2)\n{matrix1<matrix2}')

matrix1:
[2 2 3 4 9]
matrix2:
[5 4 8 2 7]

np.equal(if matrix1 == matrix2)
[False False False False False]

np.not_equal(if matrix1 != matrix2)
[ True  True  True  True  True]

np.greater(if matrix1 > matrix2)
[False False False  True  True]

np.greater_equal(if matrix1 < matrix2)
[ True  True  True False False]


In [108]:
matrix1 = np.random.randint(1,10, size=5)
matrix2 = np.random.randint(1,10, size=5)

print(f'matrix1:\n{matrix1}')
print(f'matrix2:\n{matrix2}')

print(f'\nnp.equal(if matrix1 == matrix2)\n{matrix1==arr2}')
print(f'\nnp.not_equal(if matrix1 != matrix2)\n{matrix1!=matrix2}')

print(f'\nnp.less(if matrix1 > matrix2)\n{matrix1>matrix2}')
print(f'\nnp.less_equal(if matrix1 < matrix2)\n{matrix1<matrix2}')

matrix1:
[8 8 6 9 5]
matrix2:
[1 2 6 2 6]

np.equal(if matrix1 == matrix2)
[False  True False  True False]

np.not_equal(if matrix1 != matrix2)
[ True  True False  True  True]

np.less(if matrix1 > matrix2)
[ True  True False  True False]

np.less_equal(if matrix1 < matrix2)
[False False False False  True]


## 6. Searching NumPy Arrays using `numpy.where()`


### a. Searching NumPy 1-D Arrays

- The `numpy.where()` method is used to search NumPy arrays for the index values of any element which matches the condition passed as a parameter to the function.
```
numpy.where(condition, [x, y])
```
    - condition : When True, yield x, otherwise yield y. If x and y are not given just return the value of the array
    - Returns: ndarray or tuple of ndarrays. If both x and y are specified, the output array contains elements of x where condition is True, and elements from y elsewhere.

In [110]:
arr = np.array([6,5,4,80,10,21,23,67,90])
a1 = np.where(arr == 4)
print(a1)

(array([2], dtype=int64),)


Note: The result is a tuple of 1-D arrays having a single tuple containing the index

In [111]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
t1 = np.where(arr%2 == 0)
print(t1)

(array([1, 3, 5, 7], dtype=int64),)


In [112]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
t1 = np.where(arr%2 == 0, True, False)
print(t1)

[False  True False  True False  True False  True]


In [113]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
t1 = np.where(arr%2 == 0, 'Yes', 'No')
print(t1)

['No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes']


Note: The result is a simple 1-D array, when you use the x and y arguments to `np.where()`

### b. Searching NumPy 2-D Arrays

- The `numpy.where()` method is used to search NumPy arrays for the index values of any element which matches the condition passed as a parameter to the function.
```
numpy.where(condition, [x, y])
```
    - condition : When True, yield x, otherwise yield y. If x and y are not given just return the value of the array
    - Returns: ndarray or tuple of ndarrays. If both x and y are specified, the output array contains elements of x where condition is True, and elements from y elsewhere.

In [117]:
matrix = np.random.randint(1,20, size=(4,4))
print(f'Matrix:\n{matrix}')


Matrix:
[[11 10  1  9]
 [ 9 15  1 15]
 [13 12 11 16]
 [16 15  1 15]]
(array([0, 2], dtype=int64), array([0, 2], dtype=int64))


In [120]:
t1 = np.where(matrix == 15)
print(f'There are 11 at the cordinates:\n{t1}')
# coordinate is numbers from each array

There are 11 at the cordinates:
(array([1, 1, 3, 3], dtype=int64), array([1, 3, 1, 3], dtype=int64))


**Note:** The result is a tuple of 1-D arrays having two tuples. The condition is true for three elements at indices `(1,1)`, `(1,3)`,  `(3,1)` and `(3,3)`

In [121]:
t1 = np.where(matrix%2 == 0)
print(t1)

(array([0, 2, 2, 3], dtype=int64), array([1, 1, 3, 0], dtype=int64))


**Note:** The result is a tuple of 1-D arrays having two tuples. The condition is true for three elements at indices `(0,1)`, `(2,1)`,  `(2,3)` and `(3,0)`

In [123]:
t1 = np.where(matrix%2 == 0, True, False)
print(t1)

[[False  True False False]
 [False False False False]
 [False  True False  True]
 [ True False False False]]


**Note:** The result is a simple 2-D array, when you use the `x` and `y` arguments to `np.where()`

In [125]:
t1 = np.where(matrix%2 == 0, "Even", "Odd")
print(t1)

[['Odd' 'Even' 'Odd' 'Odd']
 ['Odd' 'Odd' 'Odd' 'Odd']
 ['Odd' 'Even' 'Odd' 'Even']
 ['Even' 'Odd' 'Odd' 'Odd']]
