..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/

<img align="center" width="500" height="500"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/indexingandslicing.png" > 

# Learning agenda of this notebook
Indexing and Slicing are two of the most common operations that you need to be familiar with when working with Numpy arrays. You will use them when you would like to work with a subset of the array.
1. Indexing NumPy Arrays
    - Indexing 1-D NumPy Arrays
    - Indexing 2-D NumPy Arrays
    - Indexing 3-D NumPy Arrays
2. Slicing NumPy Arrays
    - Slicing 1-D NumPy Arrays
    - Slicing 2-D NumPy Arrays
3. Boolean Array Indexing
    - Boolean Indexing on 1-D NumPy Arrays
    - Boolean Indexing on 2-D NumPy Arrays

In [2]:
import numpy as np
np.__version__ , np.__path__

('1.24.3', ['C:\\Users\\FashN\\anaconda3\\Lib\\site-packages\\numpy'])

In [4]:
import numpy as np
mylist = [4,23,10,0,-4,-31]
arr = np.array(mylist, dtype=np.uint8)

print(f"Original Array:\n{mylist}")

Original Array:
[4, 23, 10, 0, -4, -31]


C:\Users\FashN\AppData\Local\Temp\ipykernel_9324\2679122254.py:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -4 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  arr = np.array(mylist, dtype=np.uint8)
C:\Users\FashN\AppData\Local\Temp\ipykernel_9324\2679122254.py:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -31 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  arr = np.array(mylist, dtype=np.uint8)


In [7]:
mylist = [4, 5, 6, 7, 0, 2, 3]
arr = np.array(mylist, dtype=np.uint8)

# You can access specific elements using positive as well as negative index
print(f'arr[0] = {arr[0]}')
print(f'arr[5] = {arr[5]}')
print(f'arr[-1] = {arr[-1]}')
print(f'arr[-5] = {arr[-5]}')

arr[0] = 4
arr[5] = 2
arr[-1] = 3
arr[-5] = 6


### b. Indexing 2-D NumPy Arrays

In [9]:
mylist = [
          [1, 2, 3, 4], 
          [5, 6, 7, 8], 
          [3, 2, 4, 1], 
          [7, 3, 4, 9], 
          [4, 0, 3, 1]
          ]
arr = np.array(mylist)
print(f"Original Array:\n{arr} \nArray Shape: {arr.shape}\nStrides:{arr.strides}")

# You can access specific elements
print("arr[3][2] = ", arr[3][2])
print("arr[3,2] = ", arr[3,2])


# You can access entire rows
print("arr[3] = ", arr[3])

# Negative indexing
print("arr[-1][-2] = ", arr[-1][-2])    
print("arr[-1, -2] = ", arr[-1, -2]) 
print("arr[-3][-3] = ", arr[-3][-3])    
print("arr[-3, -3] = ", arr[-3, -3])    
print("arr[-3] = ", arr[-3])       
print("arr[-1] = ", arr[-1])    

Original Array:
[[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]] 
Array Shape: (5, 4)
Strides:(16, 4)
arr[3][2] =  4
arr[3,2] =  4
arr[3] =  [7 3 4 9]
arr[-1][-2] =  3
arr[-1, -2] =  3
arr[-3][-3] =  2
arr[-3, -3] =  2
arr[-3] =  [3 2 4 1]
arr[-1] =  [4 0 3 1]


### c. Indexing 3-D NumPy Arrays

In [10]:
mylist = [
          [[1, 2, 3], [5, 6, 7], [9, 0, 5]],
          [[8, 1, 6], [1, 9, 4], [5, 8, 2]],
         ]
arr = np.array(mylist)
print(f"Original Array:\n{arr} \nArray Shape: {arr.shape}\nStrides:{arr.strides}")


Original Array:
[[[1 2 3]
  [5 6 7]
  [9 0 5]]

 [[8 1 6]
  [1 9 4]
  [5 8 2]]] 
Array Shape: (2, 3, 3)
Strides:(36, 12, 4)


In [14]:
# You can access 2-D matrix at first level
print(f'\narr[0]=\n\n{arr[0]}\n\narr[1]=\n\n{arr[1]}')


arr[0]=

[[1 2 3]
 [5 6 7]
 [9 0 5]]

arr[1]=

[[8 1 6]
 [1 9 4]
 [5 8 2]]


In [18]:
print(f'Array Shape = {arr.shape}')
print(f"arr[0][1] = {arr[0][1]}")
print(f"arr[1][2] = {arr[1][2]}")
print(f"arr[1][0] = {arr[1][0]}")
print(f"arr[1][1] = {arr[1][1]}")
# You can access a specific row at a specific level

Array Shape = (2, 3, 3)
arr[0][1] = [5 6 7]
arr[1][2] = [5 8 2]
arr[1][0] = [8 1 6]
arr[1][1] = [1 9 4]


In [19]:
print(f"arr[1][2][0] = {arr[1][2][0]}")
print(f"arr[1][2][1] = {arr[1][2][1]}")

arr[1][2][0] = 5
arr[1][2][1] = 8


In [20]:
print(f"arr[-1][-2][-1] = {arr[-1][-2][-1]}")
print(f'arr[-2][1] = {arr[-2][1]}')

arr[-1][-2][-1] = 4
arr[-2][1] = [5 6 7]


## 2. Slicing NumPy Arrays
- You can slice a numpy array in a similar fashion as we have sliced Python Lists, with two differences:
    - The difference is that NumPy arrays can be sliced in more than one dimension.
    - The other difference is that, when we slice a Python list we get a completely new list, while in case of numPy arrays, you get a **view** of the original array, which is just a way of accessing array data. Thus the original array is not copied in memory.
- An array can be sliced using `:` symbol, which returns the range of elements specified by the index numbers.
- There are three arguments for slicing arrays, all are optional:
```
array[[start]:[stop][:step]]
```

    - start: specifies from where the slicing should start, inclusive (default is 0) 
    - stop: specifies where it has to stop, exclusive (default is end of the array) 
    - step:  is by-default 1
    
Note: Subarrays that are extracted from arrays using slice operations are alternative views of the same underlying array data. This means that they are arrays that refer to the same data in memory as the original array, but with a different strides configuration.

### a. Slicing 1-D Arrays

In [23]:
import numpy as np
mylist = [-4,12,3,10,-6,9,18]
arr = np.array(mylist)
print(f'Original Array:\n{arr}\nArray Shape = {arr.shape}')

Original Array:
[-4 12  3 10 -6  9 18]
Array Shape = (7,)


In [27]:
print(f'\narr[:] = {arr[:]}')
print(f'\narr[3:] = {arr[3:]}')
print(f'\narr[2:5] = {arr[2:5]}')

print(f'\narr[:-2] = {arr[:-2]}')
print(f'\narr[-1:] = {arr[-1:]}')
print(f'\narr[-1:-4:-1] = {arr[-1:-4:-1]}')

# reverse the array using step value as -1
print(f'arr[::-1] = {arr[::-1]}')


arr[:] = [-4 12  3 10 -6  9 18]

arr[3:] = [10 -6  9 18]

arr[2:5] = [ 3 10 -6]

arr[:-2] = [-4 12  3 10 -6]

arr[-1:] = [18]

arr[-1:-4:-1] = [18  9 -6]
arr[::-1] = [18  9 -6 10  3 12 -4]


**Proof of Concept:** Slice of a Python List Returns a New List

In [28]:
list1 = [1, 2, 3, 4, 5, 6, 7,8, 9]
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [29]:
# A new list object is created after slicing
list2=list1[2:5]
list2

[3, 4, 5]

In [32]:
#If we make change to this list, it do not effect the original list
list2[2] = 101

print(f'List2 = {list2}')
print(f'List1 = {list1}')

List2 = [3, 4, 101]
List1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]


In [31]:
list2

[3, 4, 5]

**Proof of Concept:** Slice of a numPy array returns a **view** of original numPy array

In [33]:
list1 = [1, 2, 3, 4, 5, 6, 7,8, 9]
arr1 = np.array(list1)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
# A view of the original numPy array is created after slicing
arr2 = arr1[2:5]
arr2

array([3, 4, 5])

In [36]:
# If we make change to this view, it will ofcourse effect the original array
arr2[0] = 111
print(f'Arr2 = {arr2}')
print(f'Arr1 = {arr1}')

Arr2 = [111   4   5]
Arr1 = [  1   2 111   4   5   6   7   8   9]


In [37]:
arr1

array([  1,   2, 111,   4,   5,   6,   7,   8,   9])

### b. Slicing 2-D Arrays
- Slicing a two-dimensional array is very similar to slicing a one-dimensional array. You just use a comma to separate the row slice and the column slice.
- Numpy extends Python's list indexing notation using `[]` to multiple dimensions in an intuitive fashion. You can provide a comma-separated list of indices or ranges to select a specific element or a subarray (also called a slice) from a Numpy array.

In [38]:
import numpy as np
mylist = [
          [1, 2, 3, 4], 
          [5, 6, 7, 8], 
          [3, 2, 4, 1], 
          [7, 3, 4, 9], 
          [4, 0, 3, 1]
          ]
arr = np.array(mylist)
print("Original Array \n", arr, "\nArray Size = ",arr.shape)

Original Array 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]] 
Array Size =  (5, 4)


In [45]:
# Note we have two slice objects (row slice and column slice) in case of 2-D slicing separated by a comma
print(f"\narr[:,:] = \n {arr[:,:]}")

print(f'\nOriginal Array \n {arr}\nArray Size = {arr.shape}')

# you can ignore the : symbol for the column part
print(f'\narr[2] = {arr[2]}')

# for better readability give comma separated two values
print(f'\narr[2: ] = \n\n{arr[2: ]}')


arr[:,:] = 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]]

Original Array 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]]
Array Size = (5, 4)

arr[2] = [3 2 4 1]

arr[2: ] = 

[[3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]]


In [47]:
# Get the column at index 1 (Get all the row values of column at index 1)
print("arr[:, 1] = ", arr[:, 1])

# From the row at index 1, slice elements from index 1 to index 2
print("\narr[1, 1:3] = ",arr[1, 1:3])

arr[:, 1] =  [2 6 2 3 0]

arr[1, 1:3] =  [6 7]


In [48]:
print("Original Array \n", arr, "\nArray Size = ",arr.shape)

# Reversing elements of all rows is tricky. 
# Read it as "select all the rows, and in each row reverse all the column values
print("\narr[:, ::-1] =\n", arr[:, ::-1])

Original Array 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]] 
Array Size =  (5, 4)

arr[:, ::-1] =
 [[4 3 2 1]
 [8 7 6 5]
 [1 4 2 3]
 [9 4 3 7]
 [1 3 0 4]]


In [49]:
print("Original Array \n", arr, "\nArray Size = ",arr.shape)

# Reverse elements of all columns is also tricky. Actually you want to reverse the elements of all the rows
# Read it as "select all the columns, and in each column reverse all the row values
print("\narr[::-1, :] =\n", arr[::-1, :])

Original Array 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]] 
Array Size =  (5, 4)

arr[::-1, :] =
 [[4 0 3 1]
 [7 3 4 9]
 [3 2 4 1]
 [5 6 7 8]
 [1 2 3 4]]


>- **Slicing 3-D arrays can be performed in the same fashion. The only difference is that we have three comma separated slice objects instead of two and it is a bit tricky to visualize :)**

In [58]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [3, 2, 4, 1], [7, 3, 4, 9], [4, 0, 3, 1] ])
print(f'Arrays shape = {arr.shape}')
print(arr[3,2])
print(arr[3])
print(arr[-1,2])
print(arr[-1][-2])
print(arr[-3])
print(arr[-3][-3])

Arrays shape = (5, 4)
4
[7 3 4 9]
3
3
[3 2 4 1]
2


In [70]:
print(arr[2, 1:3])
print(arr[::-1,:])
print()
print(arr[2::, 0::2])

[2 4]
[[4 0 3 1]
 [7 3 4 9]
 [3 2 4 1]
 [5 6 7 8]
 [1 2 3 4]]

[[3 4]
 [7 4]
 [4 3]]


## 3. Boolean/Fancy Array Indexing

- NumPy provides another convenient method to index arrays, called fancy indexing. With fancy indexing, an array can be indexed with another NumPy array, a Python list, or a sequence of integers, whose values select elements in the indexed array. Fancy indexing requires that the elements in the array or list used for indexing are integers.

- Boolean indexing is an extremely intuitive and elegant way of selecting contents from a numPy array based on logical conditions.
- In simple words, we can slice NumPy arrays by either:
    - Provide a condition inside the `[]` operator
    - Provide a Boolean mask corresponding to indexes in the array.
- If the value at an index of that list is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

>- **Note:** Unlike normal slicing which creates a view, Boolean/Fancy Indexing creates a copy of numPy array.

>- **Note:** The Python keywords `and` and `or` do not work with boolean arrays. Use `&` and `|` instead

### a. Boolean/Fancy Indexing on 1-D Arrays

In [78]:
# Fancy Indexing
import numpy as np
# creating 1-D array of size 10 of int type b/w interval (1,100) 
arr = np.random.randint(1, 101, 10)
print(f"Original Array = \n{arr}")
print(f'\n\narr([0,2,4,9]) = {arr[np.array([0,2,4,9])]}')
print()
print(arr[[0,3,4,9]])

Original Array = 
[ 53  20  81 100  49  87   1  84 100  33]


arr([0,2,4,9]) = [53 81 49 33]

[ 53 100  49  33]


In [87]:
# Boolean Indexing
# creating 1-D array of size 10 of int type b/w interval (1,100) 
arr = np.random.randint(1, 101, 10)
print(f"Original Array = {arr}")
print(arr > 50)
print(arr[arr>50])

# Getting even values from array
print(f"\n[arr%2==0] = {arr[arr%2==0]}")

# Getting odd values from array
print(f"\n[arr%2==1] = {arr[arr%2==1]}")

# Getting values greater than 50
print(f"\n[arr > 50] = {arr[arr > 50]}")

# Getting values between 25 and 75
print(f"\n[arr > 50] = {arr[(arr > 25) & (arr < 75)]}")

Original Array = [12 94 67 82 69  8 68 76 55 14]
[False  True  True  True  True False  True  True  True False]
[94 67 82 69 68 76 55]

[arr%2==0] = [12 94 82  8 68 76 14]

[arr%2==1] = [67 69 55]

[arr > 50] = [94 67 82 69 68 76 55]

[arr > 50] = [67 69 68 55]


In [91]:
# We can use a mask instead of mentioning a condition as done above
arr1 = np.array([10, 24, 63, 44, 15])
print(f'Original Array = \n{arr1}')

mask=[False, True, False, True, False]
arr2 = arr1[mask]

print(f'Filtered Array = {arr2}')

Original Array = 
[10 24 63 44 15]
Filtered Array = [24 44]


### b. Boolean/Fancy Indexing on 2-D Arrays

>Suppose we want a new matrix from above matrix, that only contains rows at index 0, 2, and 3

In [97]:
# By passing a tuple to size means rows and columns
matrix1 = np.random.randint(low=1, high=10, size = (5,5))

print(f"Original Matrix =\n{matrix1}\nMatrix shape = {matrix1.shape}")

# Create a corresponding boolean mask
rows_wanted = np.array( [True, False, True, True, False] )
matrix2 = matrix1[rows_wanted]

print(f'\nFiltered matrix = \n{matrix2}\nMatrix.shape = {matrix2.shape}')


Original Matrix =
[[9 9 5 9 2]
 [2 3 3 1 8]
 [5 8 1 8 5]
 [9 2 1 1 5]
 [5 4 7 7 3]]
Matrix shape = (5, 5)

Filtered matrix = 
[[9 9 5 9 2]
 [5 8 1 8 5]
 [9 2 1 1 5]]
Matrix.shape = (3, 5)


**Example 2:**

In [99]:
# By passing a tuple to size means rows and columns
matrix1 = np.random.randint(low=1, high=15, size=(5,5))
print(f'Original matrix = \n{matrix1} \n\nMatrix Shape = {matrix1.shape}')

Original matrix = 
[[14 12 13  6  7]
 [10  7  5  6  5]
 [11  9  4  6  5]
 [ 1  1  8  7 13]
 [10  3  5  7  4]] 

Matrix Shape = (5, 5)


In [101]:
# Create a corresponding boolean mask
cols_wanted = np.array([False, True, False, True, False])

matrix2 = matrix1[:, cols_wanted]
print(f'Filtered matrix = \n{matrix2} \n\nMatrix Shape = {matrix2.shape}')

Original matrix = 
[[12  6]
 [ 7  6]
 [ 9  6]
 [ 1  7]
 [ 3  7]] 

Matrix Shape = (5, 2)


In [102]:
# By passing a tuple to size means rows and columns
matrix1 = np.random.randint(low = 4, high = 15, size = (5,5))
print(f'Original matrix = \n{matrix1} \n\nMatrix Shape = {matrix1.shape}')

Original matrix = 
[[ 6  8  5 11  9]
 [13  6 11 13  7]
 [12  9 13 14 13]
 [ 6 10  4  9 14]
 [ 9  9  4 14 14]] 

Matrix Shape = (5, 5)


>Suppose we want a new matrix from above 5x5 matrix, that contains inner 3x3 matrix

In [107]:
rows_wanted = np.array( [False, True, True, True, False] )

matrix2 = matrix1[ rows_wanted , :]
print(f'Filtered matrix = \n{matrix2} \n\nMatrix Shape = {matrix2.shape}')

Filtered matrix = 
[[13  6 11 13  7]
 [12  9 13 14 13]
 [ 6 10  4  9 14]] 

Matrix Shape = (3, 5)


In [106]:
cols_wanted = np.array( [False, True, True, True, False] )

matrix3 = matrix2[ :, cols_wanted]
print(f'Matrix2 = \n{matrix2}\n\nFiltered matrix = \n{matrix3} \n\nMatrix Shape = {matrix3.shape}')

Matrix2 = 
[[13  6 11 13  7]
 [12  9 13 14 13]
 [ 6 10  4  9 14]]

Filtered matrix = 
[[ 6 11 13]
 [ 9 13 14]
 [10  4  9]] 

Matrix Shape = (3, 3)


In [108]:
matrix3 = matrix1[1:4, 1:4]
print("\nFiltered matrix \n", matrix3, "\nMatrix Shape = ",matrix3.shape)


Filtered matrix 
 [[ 6 11 13]
 [ 9 13 14]
 [10  4  9]] 
Matrix Shape =  (3, 3)


In [110]:
matrix2 = matrix1[ 1 : -1,  1 : -1 ]
matrix2

print(f'Original Matrix = \n{matrix1}\n\nFiltered matrix = \n{matrix2} \n\nMatrix Shape = {matrix2.shape}')

Original Matrix = 
[[ 6  8  5 11  9]
 [13  6 11 13  7]
 [12  9 13 14 13]
 [ 6 10  4  9 14]
 [ 9  9  4 14 14]]

Filtered matrix = 
[[ 6 11 13]
 [ 9 13 14]
 [10  4  9]] 

Matrix Shape = (3, 3)


# Four Slicing Problems with Solutions

<img align="center" width="500" height="500"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/slicingQ.jpeg" > 

In [111]:
m1 = np.array([
            [0,1,2,3,4,5],
            [6,7,8,9,10,11],
            [12,13,14,15,16,17],
            [18,19,20,21,22,23],
            [24,25,26,27,28,29],
            [30,31,32,33,34,35]
])

In [112]:
m1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [113]:
m1[0, 3:5]

array([3, 4])

In [114]:
m1[4:, 4:]

array([[28, 29],
       [34, 35]])

In [116]:
m2 = m1[:,2]
m2

array([ 2,  8, 14, 20, 26, 32])

In [117]:
m2.strides

(24,)

In [119]:
m1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [120]:
m1[2::2, 0::2]
# taking everything in the row number 2,
# then step 2, then from index 0,take all columns, every 2 steps


array([[12, 14, 16],
       [24, 26, 28]])

In [122]:
m1[:,0::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [30, 32, 34]])