## 1. Introduction to Numpy Library
<img align="right" width="500" height="300"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/ndarrays.png" > 

- *A **NumPy array** (https://numpy.org) is a numerically ordered sequence of elements stored contiguously in memory, that can store elements of homogeneous types (usually numbers but can be boolians, strings, or other objects), is iterable, mutable, non-growable/shrinkable and allows duplicate elements.*
- Some attributes of NumPy Array:
>- **ndim:** The number of dimensions, can be 1, 2, 3, ... N
>- **axis:** Each dimension is called an axis: `axis 0` is the vertical axis, goes from top to bottom, represents the number of rows, `axis 1` is the horizontal axis, goes from left to right, represents the number of columns, `axis 2` is the number of columns along z axis
>- **rank:** The number of axes is called the rank.
>- **shape:** It is a tuple whose length is the rank and elements are dimension of each axis.
>- **size:** It is the total number of elements, which is the product of all axis lengths.
>- **itemsize:** It gives you the size in bytes of each element of the array (depends on dtype).
>- **nbytes:** It gives you the total number of bytes occupied by entire array object in memory (size x itemsize).

In [1]:
import sys
!{sys.executable} -m pip install --upgrade pip

   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
    --------------------------------------- 0.0/2.1 MB 130.7 kB/s eta 0:00:16
    --------------------------------------- 0.0/2.1 MB 130.7 kB/s eta 0:00:16
    --------------------------------------- 0.0/2.1 MB 130.7 kB/s eta 0:00:16
    --------------------------------------- 0.0/2.1 MB 130.7 kB/s eta 0:00:16
   - -------------------------------------- 0.1/2.1 MB 218.5 kB/s eta 0:00:10
   - -------------------------------------- 0.1/2.1 MB 218.5 kB/s eta 0:00:10
   - -------------------------------------- 0.1/2.1 MB 218.5 kB/s eta 0:00:10
   -- ----------------------------------

In [2]:
import numpy as np
np.__version__ , np.__path__

('1.24.3', ['C:\\Users\\FashN\\anaconda3\\Lib\\site-packages\\numpy'])

## 2.  Array Creation using `np.array()` Constructor
<img align="right" width="500" height="400"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/numpytypes.png" > 

```
np.array(seq, dtype)
```
- The only required argument is a sequence like object like a list from which to create an array
- The optional `dtype` argument specifies the data type of the array objects. 
- For integer values it is normally int64
- For float values it is normally float64.
- You can mention `dtype` if you want to limit memory usage. 

In [5]:
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64],
 'complex': [numpy.complex64, numpy.complex128],
 'others': [bool, object, bytes, str, numpy.void]}

In [8]:
arr = np.array([])
print(arr)
print(type(arr))

[]
<class 'numpy.ndarray'>


In [9]:
print("array: ", arr)
print("arr.ndim: ", arr.ndim)   # get number of dimensions (an empty array has number of dimensions equals to 1)
print("arr.shape: ", arr.shape) # This is an empty array, so have a shape of (0, )
print("arr.size: ", arr.size)   # get total number of elements
print("arr.dtype: ", arr.dtype) # get data type, default for empty array is float64
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array default is 8 for float64
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory

print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array:  []
arr.ndim:  1
arr.shape:  (0,)
arr.size:  0
arr.dtype:  float64
arr.itemsize:  8
arr.nbytes:  0
arr.data:  <memory at 0x000001BA83ADEEC0>
arr.strides:  (0,)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [10]:
# Create a 0-D numpy array using array() constructor
arr = np.array(10)
print(arr)

10


In [11]:
print("array: ", arr)
print("arr.ndim: ", arr.ndim)   # get number of dimensions (a 0-D array has number of dimensions equals to 0)
print("arr.shape: ", arr.shape) # This is a scalar value, so have no shape ( )
print("arr.size: ", arr.size)   # get total number of elements, in this case it is 1
print("arr.dtype: ", arr.dtype) # get data type, default is what is minimum required to hold the only element
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array default is 8 for int64
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory

print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array:  10
arr.ndim:  0
arr.shape:  ()
arr.size:  1
arr.dtype:  int32
arr.itemsize:  4
arr.nbytes:  4
arr.data:  <memory at 0x000001BA82FDA5C0>
arr.strides:  ()
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



### c.  1-Dimensional Arrays
<img align="left" width="200" height="100"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/1d.png" > 

- An array that has 0-D arrays or scalar values, as its elements is called a 1-D array. 
- Used to represent vectors or 1st order tensors.
- A 1-D array has only one axis:
    - **axis 0:** or vertical axis   or x-axis or number of rows

In [12]:
# ..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/

In [14]:
arr = np.array([[2,1,-3], [7,89,0], [-2,16,22]])

In [15]:
arr

array([[ 2,  1, -3],
       [ 7, 89,  0],
       [-2, 16, 22]])

In [16]:
for i in range(3):
    for j in range(3):
        print(arr[i, j])

2
1
-3
7
89
0
-2
16
22


In [19]:
mylist = [5, 7, 18, 32, 56, -9]
arr = np.array(mylist, dtype=np.uint8)
arr

C:\Users\FashN\AppData\Local\Temp\ipykernel_9892\3935699442.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -9 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  arr = np.array(mylist, dtype=np.uint8)


array([  5,   7,  18,  32,  56, 247], dtype=uint8)

In [10]:
# creating 2-D (5x4) array using array constructor in numpy
import numpy as np
mylist = [
          [1, 2, 3, 4], 
          [5, 6, 7, 8], 
          [3, 2, 4, 1], 
          [7, 3, 4, 9], 
          [4, 0, 3, 1]
          ]
arr = np.array(mylist)
print("array: \n",arr)

array: 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]]


In [11]:
arr[1][1]

6

In [12]:
arr[1,1]

6

In [19]:
mylist = [[1],[5],[8],[-5]]
arr = np.array(mylist)
print("array:\n",arr)

print("\nndim:", arr.ndim)
print("shape:", arr.shape)


array:
 [[ 1]
 [ 5]
 [ 8]
 [-5]]

ndim: 2
shape: (4, 1)


### e.  3-Dimensional Arrays
<img align="left" width="200" height="100"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/3d.png" > 

- An array that has 2-D arrays as its elements is called a 3-D array. Used to represent 3rd order tensors.
- A 3-D array has three axis:
    - **axis 0:** represent the number of rows along x-axis(axis 0). (5)
    - **axis 1:** represents the number of rows along y-axis (axis 1). (4)
    - **axis 2:** represents the number of columns along z-axis (axix 2). (3)

In [21]:
# creating 3-D (5x4x3) array using array constructor in numpy
mylist = [
          [[1, 2, 3], [5, 6, 7], [3, 2, 4], [7, 3, 4]],
          [[8, 1, 6], [1, 9, 4], [5, 6, 4], [2, 6, 2]],
          [[5, 3, 2], [2, 0, 5], [8, 3, 0], [5, 6, 9]],
          [[6, 7, 1], [8, 1, 6], [1, 4, 7], [2, 0, 4]],
          [[2, 8, 9], [3, 0, 4], [5, 2, 2], [1, 3, 8]],
         ]
arr = np.array(mylist, dtype=np.uint8)
print("array:\n", arr)

array:
 [[[1 2 3]
  [5 6 7]
  [3 2 4]
  [7 3 4]]

 [[8 1 6]
  [1 9 4]
  [5 6 4]
  [2 6 2]]

 [[5 3 2]
  [2 0 5]
  [8 3 0]
  [5 6 9]]

 [[6 7 1]
  [8 1 6]
  [1 4 7]
  [2 0 4]]

 [[2 8 9]
  [3 0 4]
  [5 2 2]
  [1 3 8]]]


### Understanding Strides

In [22]:
# Strides of 1-D array
import numpy as np
mylist = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
arr = np.array(mylist, dtype=np.int64)

print("array: \n", arr)
print("arr.data: ", arr.data)
print("arr.shape: ", arr.shape)  
print("arr.dtype: ", arr.dtype)  
print("arr.size: ", arr.size)    
print("arr.itemsize: ", arr.itemsize) 
print("arr.nbytes: ", arr.nbytes)  
print("arr.strides: ", arr.strides)
# Use of strides is in Indexing, slicing and reshaping
print(arr[3]) # jump 3*8=24 bytes and then read 8 bytes

array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
arr.data:  <memory at 0x000001BD40652500>
arr.shape:  (12,)
arr.dtype:  int64
arr.size:  12
arr.itemsize:  8
arr.nbytes:  96
arr.strides:  (8,)
3


In [29]:
# Strides od 2-D array
import numpy as np
mylist = [[0,1,2,3], [9,8,7,6], [12,23,45,67]]
arr = np.array(mylist, dtype=np.int64)

print("ARRAY:\n", arr)
print("\narray[1,2]:",arr[1,2])

ARRAY:
 [[ 0  1  2  3]
 [ 9  8  7  6]
 [12 23 45 67]]

array[1,2]: 7


In [32]:
# Strides of 3-D array
import numpy as np
mylist = [
          [[0, 1], [2, 3]],
          [[4, 5], [6, 7]],
          [[8, 9], [10, 11]]
            ]
arr = np.array(mylist, dtype=np.int64)
print("array:\n", arr)

array:
 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


<img align="right" width="150" height="100"  src="images/zeros.png"  > 

### a. Using `np.zeros()` Method
This method returns an array of given shape and type, filled with zeros.

```
numpy.zeros(shape, dtype=float)
```

- shape : The shape is an int or tuple of ints to define the size/shape of the array.
- dtype : The dtype is an optional parameter with default value as float.

In [33]:
# Creating 1-Dimensional array of all zeros
arr = np.zeros(3)
arr
# Notice that the elements are having the default data type as the float. That’s why the zeros are 0.

array([0., 0., 0.])

In [34]:
# Creating 2-Dimensional array filled with zeros
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
# Creating 2-Dimensional array filled with zeros of integer types
arr = np.zeros((2,3), dtype=np.int16)
print(arr)
print(arr.nbytes)

[[0 0 0]
 [0 0 0]]
12


<img align="right" width="100" height="100"  src="images/ones.png"  > 

### b. Using `np.ones()` Method
This method returns an array of given shape and type, filled with ones.

```
numpy.ones(shape, dtype=float)
```

- shape : The shape is an int or tuple of ints to define the size/shape of the array.
- dtype : The dtype is an optional parameter with default value as float.

In [38]:
# Creating one-dimensional array with ones
arr = np.ones(3)
arr

array([1., 1., 1.])

In [40]:
# Creating 2-Dimensional array having 3 columns filled with ones
arr = np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
# Creating 2-Dimensional array having 3 columns filled with ones of integer types
arr = np.ones((2,3), dtype=np.int16)
arr

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

<img align="right" width="250" height="100"  src="images/empty.png"  > 

### c. Using `np.empty()` Method
This method returns an array of given shape and type, filled with junk values.

```
numpy.empty(shape, dtype=float)
```

- shape : The shape is an int or tuple of ints to define the size/shape of the array.
- dtype : The dtype is an optional parameter with default value as float.


Un-like numpy.zeros(), and numpy.ones(), the numpy.empty() function doesn't initialize the entries, so they contain junk values.

In [45]:
arr = np.empty(3)
arr

array([1., 1., 1.])

In [43]:
arr = np.empty(3, dtype=np.int16)
arr

array([257, 257, 257], dtype=int16)

In [46]:
# Creating 2-Dimensional array having 3 columns filled with junk values
arr = np.empty((2,3), dtype=np.int16)
arr

array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [48]:
arr = np.empty(4)
arr

array([2.12199579e-314, 9.44288127e-312, 7.35169681e-321, 3.79442416e-321])

<img align="right" width="200" height="100"  src="images/full.png"  > 

### d. Using `np.full()` Method
This method return a new array of given shape and type, filled with fill_value.
```
np.full(shape, fill_value, dtype=None)
```
- shape: Shape of the new array
- fill_value: Fill value.
- dtype	The desired data-type for the array

In [49]:
arr = np.full(7, 54)
arr

array([54, 54, 54, 54, 54, 54, 54])

In [50]:
arr = np.full(7, 21.5)
arr

array([21.5, 21.5, 21.5, 21.5, 21.5, 21.5, 21.5])

In [52]:
arr = np.full((2,3), 21.5)
arr

array([[21.5, 21.5, 21.5],
       [21.5, 21.5, 21.5]])

<img align="right" width="120" height="130"  src="images/eye.png"  >

### e. Using `np.eye()` Method
This method is used to create a 2-D array with ones on the diagonal and zeros elsewhere.

```
eye(N, M=None, k=0 , dtype=float)
```
- N: Number of rows in the output
- M: Number of columns in the output. If None, defaults to N
- k: Index of the diagonal: (Default 0) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal
- dtype: Data-type of the returned array

In [53]:
# creating 2-D array using eye function
# with 2 rows and 2 columns having 1's at on the main diagonal
eye_arr = np.eye(3,3)
eye_arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
# creating 2-D array of int type using eye function with 4 rows and 3 columns having 1's at on the main diagonal
eye_arr = np.eye(4,3, dtype=np.int8)
eye_arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]], dtype=int8)

In [59]:
# creating 2-D array of int type using eye function with 4 rows and 3 columns having 1's at one place higher
eye_arr = np.eye(4,3, k = 1, dtype=int)
eye_arr

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [58]:
# creating 2-D array of int type using eye function with 4 rows and 3 columns having 1's at one place higher
eye_arr = np.eye(4,3, k = -1, dtype=int)
eye_arr

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

<img align="right" width="200" height="150"  src="images/fromstring.png"  > 

### f. Using `np.fromstring()` Method
This function is used to create a new 1-D array initialized from raw binary or text data in a string.
```
np.fromstring(string, dtype, sep)
```
- string: A string containing the data
- dtype: The data type of the array (by default float)
- sep: The string separating numbers in the data

In [60]:
# convert the space separated string '25 30 35 40' into an integer array
arr = np.fromstring('25 30 35 43', sep=' ', dtype=np.int8)
arr

array([25, 30, 35, 43], dtype=int8)

In [61]:
# converting comma separated string into float type array
arr = np.fromstring('0.7, 10.4, 50.5', sep=',')
print(arr)

[ 0.7 10.4 50.5]


In [62]:
# It will raise error
arr = np.fromstring('0.57, str, 50.555', dtype=float, sep=',')

C:\Users\FashN\AppData\Local\Temp\ipykernel_8204\1942666505.py:2: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  arr = np.fromstring('0.57, str, 50.555', dtype=float, sep=',')


### g. Using `np.arange()` Method
<img align="right" width="200" height="100"  src="images/arrange.png"  > 
This function is used to get evenly spaced values within a given interval.

```
numpy.arange([start,] stop[, step])
```
- If only one argument is given will generate an int64 array from zero to that value (not inclusive)
- If two arguments are given then start value in inclusive, stop value is not inclusive and the default step is 1
- If three arguments are given then the third argument is the distance between two adjacent values. (default step size is 1)
- All the three arguments can be integers or floats

The image shows the array created by np.arange(5,9,1)


In [64]:
arr=np.arange(5)
print(arr)
print(type(arr))
print(arr.dtype)

[0 1 2 3 4]
<class 'numpy.ndarray'>
int32


In [65]:
arr=np.arange(5, dtype=float)
print(arr)
print(arr.dtype)

[0. 1. 2. 3. 4.]
float64


In [66]:
arr = np.arange(5,10)
arr

array([5, 6, 7, 8, 9])

In [67]:
arr = np.arange(5,20,2)
arr

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [68]:
arr = np.arange(5,20,-1)
arr

array([], dtype=int32)

In [70]:
arr = np.arange(-1, -4, -1)
arr

array([-1, -2, -3])

### h. Using `np.linspace()` Method
<img align="right" width="300" height="200"  src="images/linspace1.png"  > 

This method by default returns an array of 50 evenly spaced elements starting from the first argument (inclusive) to the second argument (inclusive). The third argument, if given, is the count of number of elements of the array, default is 50.

```
numpy.linspace(start, stop, num=50)
```

In [72]:
arr = np.linspace(2,6,4)
print(arr)
print(arr.dtype)

[2.         3.33333333 4.66666667 6.        ]
float64


In [74]:
arr = np.linspace(1,2)
print(arr)
print(arr.dtype)

[1.         1.02040816 1.04081633 1.06122449 1.08163265 1.10204082
 1.12244898 1.14285714 1.16326531 1.18367347 1.20408163 1.2244898
 1.24489796 1.26530612 1.28571429 1.30612245 1.32653061 1.34693878
 1.36734694 1.3877551  1.40816327 1.42857143 1.44897959 1.46938776
 1.48979592 1.51020408 1.53061224 1.55102041 1.57142857 1.59183673
 1.6122449  1.63265306 1.65306122 1.67346939 1.69387755 1.71428571
 1.73469388 1.75510204 1.7755102  1.79591837 1.81632653 1.83673469
 1.85714286 1.87755102 1.89795918 1.91836735 1.93877551 1.95918367
 1.97959184 2.        ]
float64


In [76]:
arr = np.linspace(-1, -5)
print(arr)

[-1.         -1.08163265 -1.16326531 -1.24489796 -1.32653061 -1.40816327
 -1.48979592 -1.57142857 -1.65306122 -1.73469388 -1.81632653 -1.89795918
 -1.97959184 -2.06122449 -2.14285714 -2.2244898  -2.30612245 -2.3877551
 -2.46938776 -2.55102041 -2.63265306 -2.71428571 -2.79591837 -2.87755102
 -2.95918367 -3.04081633 -3.12244898 -3.20408163 -3.28571429 -3.36734694
 -3.44897959 -3.53061224 -3.6122449  -3.69387755 -3.7755102  -3.85714286
 -3.93877551 -4.02040816 -4.10204082 -4.18367347 -4.26530612 -4.34693878
 -4.42857143 -4.51020408 -4.59183673 -4.67346939 -4.75510204 -4.83673469
 -4.91836735 -5.        ]


### i. Using `np.random.rand()` Method
- This method generates an array of random floats (between 0 and 1) of as many dimensions passed as argument.
- If no argument is passed, generates a scalar value between 0 and 1

```
numpy.random.rand(d0 [,d1] [,d2]....)
```


In [77]:
#Python's built-in random module has random() function that returns a single float between 0 and 1
import numpy as np
value = np.random.rand()
value

0.07671358584559707

In [78]:
arr = np.random.rand(5)
arr

array([0.03220276, 0.24879984, 0.98945767, 0.38482852, 0.16146157])

In [79]:
# Creating 1-D array of 5 elements of random floats between 0 and 10
arr = np.random.rand(5)*10
arr

array([3.82656467, 1.52838887, 6.3472615 , 3.74929908, 8.93136043])

In [80]:
# Creating 2-D array (4x3) having random floats between 0 and 1
arr = np.random.rand(4,3)*10
arr

array([[8.58964111, 6.98642691, 6.27676873],
       [0.13618868, 5.9898199 , 1.69450649],
       [2.71268396, 3.42323673, 1.70689686],
       [9.49737361, 3.97578499, 5.96059911]])

In [81]:
# Creating 3-D array of with random values using np.random.rand()
arr = np.random.rand(5,4,3)
arr

array([[[0.74150039, 0.57464206, 0.51834273],
        [0.32102782, 0.09167179, 0.12269347],
        [0.9329046 , 0.35881151, 0.86986205],
        [0.13586127, 0.91250954, 0.2443334 ]],

       [[0.69288769, 0.76177325, 0.02726624],
        [0.47960017, 0.53024349, 0.61371289],
        [0.47790292, 0.27447485, 0.95880223],
        [0.38948354, 0.26272872, 0.01733799]],

       [[0.03502657, 0.55367925, 0.73092243],
        [0.48755966, 0.29659682, 0.97235438],
        [0.48540008, 0.415295  , 0.07264377],
        [0.97982973, 0.04439281, 0.35691591]],

       [[0.88373838, 0.14093977, 0.80692888],
        [0.68583798, 0.67666809, 0.05811407],
        [0.68257014, 0.10480113, 0.41267532],
        [0.83725657, 0.21155179, 0.85110453]],

       [[0.0644142 , 0.05030886, 0.31886734],
        [0.87240173, 0.96025289, 0.4696452 ],
        [0.60728055, 0.95483561, 0.91526445],
        [0.53530648, 0.49776943, 0.1398331 ]]])

### i. Using `np.random.randint()` Method
This method returns an array of specified shape and fills it with random integers.
```
numpy.random.randint(low, high=None, size)
```
- low: Lowest (signed) integer to be drawn from the distribution. But, it works as a highest integer in the sample if high=None.
- high: Largest (signed) integer to be drawn from the distribution (not inclusive)
- size: number of samples to be generated (default is 1 for scalar and >1 for 1-D array and a tupple for ndarray)

In [82]:
# Generating a random integer scalar b/w interval (0,9) 
value = np.random.randint(10)
value

1

In [83]:
# Generating a random integer scalar b/w interval (5,19) 
value = np.random.randint(low=5, high=20)
value

18

In [85]:
# Generating a random integer scalar from -5 to 4 
value = np.random.randint(low=-5, high=5)
value

1

In [86]:
# creating 1-D array of size 6 of int type b/w interval (1,100) 
value = np.random.randint(low=-5, high=5, size=6)
value

array([ 1, -1, -2, -2, -3,  4])

In [87]:
# creating 1-D array of size 6 of int type b/w interval (-5,4) 
arr = np.random.randint(low = -5, high = 5, size = 4)
arr

array([ 3,  3, -4,  0])

In [88]:
# By passing a tuple to size means rows and columns
arr = np.random.randint(low = -5, high = 5, size = (4,5))
arr

array([[ 0, -3,  0,  1,  2],
       [ 3, -2,  0,  4,  0],
       [-5,  3, -3,  2,  1],
       [-4, -2,  0,  3, -5]])

In [89]:
arr = np.random.randint(low = 1, high = 10, size = (2,3,4))
arr

array([[[8, 1, 8, 5],
        [1, 2, 8, 1],
        [8, 4, 7, 9]],

       [[8, 2, 5, 4],
        [2, 1, 9, 3],
        [7, 6, 7, 2]]])

<img align="right" width="100" height="130"  src="images/zeros_like.png"  >

### k. Using `np.zeros_like()` Method
This method is used to get an array of zeros with the same shape and type as a given array.

```
zeros_like(arr, dtype=None) 
```

- arr: array like input
- dtype: Overrides the data type of the result

In [90]:
# creating a 2-D array
mylist = [[0,1], [2,3]]
arr = np.array(mylist)
print("A 2-D aray:\n", arr)

A 2-D aray:
 [[0 1]
 [2 3]]


In [91]:
# creating the same array as the shape of 'arr' filled with zeros
arr1 = np.zeros_like(arr)
print("\nConverted Array:\n", arr1)


Converted Array:
 [[0 0]
 [0 0]]


In [92]:
np.fromstring

<function numpy.fromstring>

In [93]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])