In [ ]:
..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/

In [1]:
import numpy as np
np.__version__, np.__path__

('1.24.3', ['C:\\Users\\FashN\\anaconda3\\Lib\\site-packages\\numpy'])

<img align="left" width="500" height="500"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/concatfunctions.png" >

# Learning agenda of this notebook

## 1. Concatenating of NumPy Arrays

<img align="right" width="500" height="200"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/concataxis1.png" >
<img align="left" width="400" height="400"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/concataxis0.png" > 

## 2. Stacking of NumPy Arrays

<img align="left" width="350" height="350"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/hs1.png" > 
<img align="right" width="350" height="350"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/vs1.png" > 

## 3. Splitting NumPy Arrays

<img align="center" width="400" height="300"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/splitting.png" > 

## 1. Concatenating NumPy Arrays
<img align="right" width="400" height="200"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/concataxis1.png" >
<img align="left" width="500" height="400"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/concataxis0.png" > 

<br><br><br><br><br><br><br><br><br><br>

The `np.concatenate()` method is used to join arrays with respect to given axis.

```
np.concatenate(tup, axis=0)
```

- Where `tup` is comma separated ndarrays
- If axis is 0, it will join the arrays by row-wise (vertically). For 2-D arrays, the number of columns must match.
- If axis is 1, it will join the arrays by column-wise (horizontally). For 2-D arrays, the number of rows must match.
- For 1-D arrays, the arrays can be of any size/length.
- The original arrays remains as such, as it does not occur in-place.

In [9]:
arr1 = np.random.randint(low=1, high=20, size=5)
arr2 = np.random.randint(low=1, high=20, size=3)

arr3 = np.concatenate((arr1, arr2))
# arr3 = np.concatenate((arr1, arr2), axis=0)

print(f"arr1 = {arr1}\narr2 = {arr2}\n arr3 = {arr3}")


arr1 = [ 7  4  5  5 19]
arr2 = [8 7 5]
 arr3 = [ 7  4  5  5 19  8  7  5]


You cannot concatenate 1-D arrays on `axis=1`, as it do not exist :)

**Example:** Concatenate two 2-D Arrays along `axis=0` (vertically/row-wise). The number of columns of two arrays must match.

In [11]:
arr1 = np.random.randint(low = 1, high = 10, size = (2,3))
arr2 = np.random.randint(low = 1, high = 10, size = (1,3))

arr3 = np.concatenate((arr1, arr2), axis=0)
print(f"arr1 = \n{arr1}\narr2 = \n{arr2}\n arr3 = \n{arr3}")


arr1 = 
[[2 4 6]
 [7 8 7]]
arr2 = 
[[7 9 5]]
 arr3 = 
[[2 4 6]
 [7 8 7]
 [7 9 5]]


**Example:** Concatenate two 2-D Arrays along `axis=1` (horizontally/column-wise). The number of rows of two arrays must match.

In [12]:
arr1 = np.random.randint(low = 1, high = 10, size = (4,3))
arr2 = np.random.randint(low = 1, high = 10, size = (4,5))

arr3 = np.concatenate((arr1, arr2), axis=1)
print(f"arr1 = \n{arr1}\narr2 = \n{arr2}\n arr3 = \n{arr3}")


arr1 = 
[[1 5 4]
 [5 8 4]
 [3 5 1]
 [4 2 9]]
arr2 = 
[[4 3 6 2 4]
 [8 1 2 5 2]
 [7 2 2 7 9]
 [8 5 2 7 3]]
 arr3 = 
[[1 5 4 4 3 6 2 4]
 [5 8 4 8 1 2 5 2]
 [3 5 1 7 2 2 7 9]
 [4 2 9 8 5 2 7 3]]


## 2. Stacking NumPy Arrays
- Concatenating joins a sequence of arrays along an existing axis, and stacking joins a sequence of arrays along existing as well as along a new axis.
- We can perform stacking along three dimensions:
    - `np.vstack()` : it performs vertical stacking along the rows.
    - `np.hstack()` : it performs horizontal stacking along with the columns.
    - `np.dstack()` : it performs in-depth stacking along a new third axis (depth).

**Note:** 
- `numpy.stack()` is the most general of the three methods, offering an axis parameter for specifying which way to put the arrays together.
- `np.column_stack()` is used to stack 1-D arrays as columns into 2-D array.
- `np.row_stack()` is used to stack 1-D arrays as rows into 2-D array.

**Example: `np.row_stack()`**

In [15]:
#ROW STACK
arr1 = np.array([2,6,11])
arr2 = np.array([3,6,9])

arr3 = np.row_stack((arr1, arr2))

print(f"arr1 = \n{arr1}\narr2 = \n{arr2}\n row stack(arr1, arr2) = \n{arr3}")

arr1 = 
[ 2  6 11]
arr2 = 
[3 6 9]
 row stack(arr1, arr2) = 
[[ 2  6 11]
 [ 3  6  9]]


**Example: `np.column_stack()`**

In [16]:
#COLUMN STACK
arr1 = np.array([2,6,11])
arr2 = np.array([3,6,9])

arr3 = np.column_stack((arr1, arr2))

print(f"arr1 = \n{arr1}\narr2 = \n{arr2}\n column stack(arr1, arr2) = \n{arr3}")

arr1 = 
[ 2  6 11]
arr2 = 
[3 6 9]
 column stack(arr1, arr2) = 
[[ 2  3]
 [ 6  6]
 [11  9]]


In [ ]:
..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/

<img align="right" width="250" height="100"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/vstackfinal.png" > 

### a. Use `np.vstack()` for Row-Wise Concatenation
The `np.vstack()` method is used to stack arrays vertically or row-wise.

```
np.vstack(tup)
```

- Where `tup` is comma separated ndarrays
- 1-D arrays must have the same size/length, while for 2-D arrays, the number of columns must match.
- It returns an ndarray formed by stacking the given arrays, will be at least 2-D.
- The original arrays remains as such, as it does not occur in-place.

In [17]:
#COLUMN STACK
arr1 = np.array([2,6,11])
arr2 = np.array([3,6,9])

arr3 = np.vstack((arr1, arr2))

print(f"arr1 = \n{arr1}\narr2 = \n{arr2}\n vstack(arr1, arr2) = \n{arr3}")

arr1 = 
[ 2  6 11]
arr2 = 
[3 6 9]
 vstack(arr1, arr2) = 
[[ 2  6 11]
 [ 3  6  9]]


Note: The output array is a 2-D array

**Example:** Perform vertical stacking of two 2-D Arrays. The number of columns of two arrays must match

In [4]:
import numpy as np
arr1 = np.random.randint(low=1, high=10, size=(2,3))
arr2 = np.random.randint(low=11, high=20, size=(3,3))
arr3 = np.vstack((arr1,arr2))

print(f"arr1 = \n{arr1}\narr2 = \n{arr2}\n vstack(arr1, arr2) = \n{arr3}")

arr1 = 
[[3 6 2]
 [6 1 7]]
arr2 = 
[[18 12 11]
 [16 12 18]
 [14 15 18]]
 vstack(arr1, arr2) = 
[[ 3  6  2]
 [ 6  1  7]
 [18 12 11]
 [16 12 18]
 [14 15 18]]


<img align="right" width="250" height="100"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/hstackfinal.png" > 

### b. Using `np.hstack()` for Column-Wise Concatenation
The `np.hstack()` method is used to stack arrays horizontally or column-wise.

```
np.hstack(tup)
```

- Where `tup` is comma separated ndarrays
- 1-D arrays can have any size/length, while for 2-D arrays, the number of rows must match.
- It returns an ndarray formed by stacking the given arrays.
- The original arrays remains as such, as it does not occur in-place.

**Example:** Perform horizontal stacking of two 1-D Arrays, which can be of different  size/length

In [7]:
arr1 = np.array([2,6,11])
arr2 = np.array([3,6,9])

arr3 = np.hstack((arr1, arr2))

print(f"arr1 = \n{arr1}\narr2 = \n{arr2}\nhstack(arr1, arr2) = \n{arr3}")

arr1 = 
[ 2  6 11]
arr2 = 
[3 6 9]
hstack(arr1, arr2) = 
[ 2  6 11  3  6  9]


Note: The output array is a 1-D array

**Example:** Perform horizontal stacking of two 2-D Arrays. The number of rows of two arrays must match

In [9]:
import numpy as np
arr1 = np.random.randint(low=1, high=10, size=(2,2))
arr2 = np.random.randint(low=11, high=20, size=(2,3))
arr3 = np.hstack((arr1,arr2))

print(f"arr1 = \n{arr1}\narr2 = \n{arr2}\nhstack(arr1, arr2) = \n{arr3}")

arr1 = 
[[4 3]
 [2 9]]
arr2 = 
[[15 16 12]
 [14 17 12]]
hstack(arr1, arr2) = 
[[ 4  3 15 16 12]
 [ 2  9 14 17 12]]


### e. Using `np.stack()`

- The `np.stack()` method is used to join a sequence of same dimension arrays along a new axis.
- The axis parameter specifies the index of the new axis in the dimensions of the result. 
- For example, if axis=0 it will be the first dimension and if axis=-1 it will be the last dimension.
```
np.stack(a1, a2, a3, ..., axis=0)
```

- Where `tup` is comma separated ndarrays
- 1-D or 2-D arrays must have the same shape, while n-D arrays must have the same shape along all but the third axis.
- It returns the array formed by stacking the given arrays, which has one more dimension than the input arrays.
- This function makes most sense for arrays with up to 3 dimensions. For instance, for pixel-data with a height (first axis), width (second axis), and r/g/b channels (third axis).



**Note:** Concatenating joins a sequence of tensors along an existing axis, and stacking joins a sequence of tensors along a new axis

**Example:** Perform stacking of two 1-D Arrays, which must have the same size/shape.

In [15]:
arr1 = np.random.randint(low = 1, high = 10, size = 4)
arr2 = np.random.randint(low = 1, high = 10, size = 4)

# Stacking two 1-D arrays along axis 0 using stack()
arr3 = np.stack((arr1,arr2), axis=0)

# Stacking the two 1-D arrays using row_stack()
arr4 = np.stack((arr1,arr2), axis=1)

# Stacking the two 1-D arrays using row_stack()
arr5 = np.row_stack((arr1,arr2))

# Stacking the two 1-D arrays using column_stack()
arr6 = np.column_stack((arr1,arr2))

print(f"arr1 = \n{arr1}\narr2 = \n{arr2}\n\nstack(arr1, arr2, axis = 0) = \n{arr3}\n\nstack(arr1, arr2, axis = 1) = \n{arr4}\n\nrow_stack = \n{arr5}\n\ncolumn_stack = \n{arr6}")

arr1 = 
[4 9 7 4]
arr2 = 
[5 5 2 1]

stack(arr1, arr2, axis = 0) = 
[[4 9 7 4]
 [5 5 2 1]]

stack(arr1, arr2, axis = 1) = 
[[4 5]
 [9 5]
 [7 2]
 [4 1]]

row_stack = 
[[4 9 7 4]
 [5 5 2 1]]

column_stack = 
[[4 5]
 [9 5]
 [7 2]
 [4 1]]


**Example:** Perform stacking of two 2-D Arrays, which must have the same size/shape.


In [17]:
arr1 = np.array([[4,3,1], [5,6,2]])
arr2 = np.array([[5,3,8], [6,9,10]])
arr3 = np.stack((arr1, arr2), axis = 0)
# Stacking the two arrays along axis 0
print(f"arr1 = \n{arr1}\narr2 = \n{arr2}\nstack((arr1, arr2), axis = 0) = \n{arr3}\narr3.shape = {arr3.shape}")

arr1 = 
[[4 3 1]
 [5 6 2]]
arr2 = 
[[ 5  3  8]
 [ 6  9 10]]
stack((arr1, arr2), axis = 0) = 
[[[ 4  3  1]
  [ 5  6  2]]

 [[ 5  3  8]
  [ 6  9 10]]]
arr3.shape = (2, 2, 3)


In [18]:
arr1 = np.array([[4,3,1], [5,6,2]])
arr2 = np.array([[5,3,8], [6,9,10]])
arr3 = np.stack((arr1, arr2), axis = 1)
# Stacking the two arrays along axis 0
print(f"arr1 = \n{arr1}\narr2 = \n{arr2}\nstack((arr1, arr2), axis = 1) = \n{arr3}\narr3.shape = {arr3.shape}")

arr1 = 
[[4 3 1]
 [5 6 2]]
arr2 = 
[[ 5  3  8]
 [ 6  9 10]]
stack((arr1, arr2), axis = 1) = 
[[[ 4  3  1]
  [ 5  3  8]]

 [[ 5  6  2]
  [ 6  9 10]]]
arr3.shape = (2, 2, 3)


## 3. Splitting NumPy Arrays
- Splitting is reverse operation of Joining, and is used to split one array into multiple arrays....
- We can perform splitting along three dimensions:
    - `np.split()` : Split array into a list of multiple sub-arrays of equal size.
    - `np.hsplit()` : Split array into multiple sub-arrays horizontally (column wise).
    - `np.vsplit()` : Split array into multiple sub-arrays vertically (row wise).

### a. The `np.split()` and `np.array_split()` Methods

<img align="left" width="400" height="200"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/split.png" > 
<img align="right" width="400" height="200"  src="images/array_split.png" > 

<br><br><br><br><br><br><br><br><br><br>
- The `np.split()` method splits an array into multiple sub-arrays of equal sizes.

```
np.split(arr, size, axis=0)
```
- Where,
    - `arr` is the array to be divided into sub-arrays.
    - `size` is an size of the sub-arrays, into which `arr` will be divided along the axis. 
    - `axis` is the axis along which to split, default is 0.
- If such split is not possible, an error is raised. To avoid error you can use `np.array_split()`
- It returns a list of sub-arrays as views into `arr`

**Example:** Use of `split()`

In [20]:
arr1 = np.random.randint(low=1, high=20, size=13)
# The array_split() will not flag an error if size is not a factor of array size (will manage)
print(f'arr1 = \n{arr1}\n\nSub-arrays: \n{np.array_split(arr1, 4)}')

arr1 = 
[ 2 18 12  9  7 14 14  6  2  9  8  1 15]

Sub-arrays: 
[array([ 2, 18, 12,  9]), array([ 7, 14, 14]), array([6, 2, 9]), array([ 8,  1, 15])]


<img align="right" width="150" height="50"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/hsplit.png" > 

### b. The `np.hsplit()` Method
- The `np.hsplit()` method is used to split an array into multiple sub-arrays horizontally (column-wise). 
- The `np.hsplit()` is equivalent to split with axis=1, the array is always split along the second axis regardless of the array dimension.

```
np.hsplit(arr, size)
```
- Where,
    - `arr` is the array to be divided into sub-arrays.
    - `size` is the size of the sub-arrays, into which `arr` will be divided along the axis. For `hsplit()`, size argument should be a factor of number of columns, else it flags an error
- It returns a list of sub-arrays as views into `arr`

In [24]:
# create an array of float type with 4 rows and 4 columns with sequential values from 0 to 15
arr1 = np.arange(20.0).reshape(5,4)

print(f'arr1 = \n{arr1}\n\nSub-arrays: \n{np.hsplit(arr1, 4)}')

arr1 = 
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]

Sub-arrays: 
[array([[ 0.],
       [ 4.],
       [ 8.],
       [12.],
       [16.]]), array([[ 1.],
       [ 5.],
       [ 9.],
       [13.],
       [17.]]), array([[ 2.],
       [ 6.],
       [10.],
       [14.],
       [18.]]), array([[ 3.],
       [ 7.],
       [11.],
       [15.],
       [19.]])]


<img align="right" width="200" height="50"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/vsplit.png" > 

### c. The `np.vsplit()` Method
- The `np.vsplit()` method is used to split an array into multiple sub-arrays vertically (row-wise). Not applicable for 1-D array.
- The `np.vsplit()` is equivalent to split with axis=0, the array is always split along the first axis regardless of the array dimension.

```
np.vsplit(arr, size)
```
-Where,
   - `arr` is the array to be divided into sub-arrays.
   - `size` is the size of the sub-arrays, into which `arr` will be divided along the axis. For `vsplit()`, size argument should be a factor of number of rows, else it flags an error
- It returns a list of sub-arrays as views into `arr`

In [32]:
# create an array of float type with 4 rows and 4 columns with sequential values from 0 to 15
arr1 = np.arange(20.0).reshape(4,5)

print(f'arr1 = \n{arr1}\narr1.shape = {arr1.shape}\n\nSub-arrays: \n{np.vsplit(arr1, 2)}')

arr1 = 
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]
arr1.shape = (4, 5)

Sub-arrays: 
[array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]]), array([[10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])]


In [33]:
import numpy as np
arr1 = np.array([2,5,1])
arr2 = np.array([3,6,2])
arr3 = np.column_stack((arr1, arr2))
arr4 = np.vstack((arr1, arr2))
arr5 = np.hstack((arr1, arr2))
arr6 = np.stack((arr1, arr2), axis = 1)
print ("arr3: ", arr3)
print ("arr4: ", arr4)
print ("arr5: ", arr5)
print ("arr6: ", arr6)

arr3:  [[2 3]
 [5 6]
 [1 2]]
arr4:  [[2 5 1]
 [3 6 2]]
arr5:  [2 5 1 3 6 2]
arr6:  [[2 3]
 [5 6]
 [1 2]]
