In [ ]:
..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/

<h1 align="center">Lecture 3.6 (NumPy-06)</h1>

# _Manipulating Array Elements.ipynb_

<img align="right" width="400" height="400"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/numpy123D.png" > 

# Learning agenda of this notebook

1. Updating existing values of NumPy array elements
2. Append new elements to a NumPy array using np.append()
3. Insert new elements in a NumPy array using np.insert()
4. Delete elements of a NumPy array using np.delete()
5. Alias vs Shallow Copy vs Deep Copy

<img align="right" width="400" height="400"  src="..\..\..\data_science\exercise\Section-3-Python-for-Data-Scientists/images/numpy123D.png" > 

# Learning agenda of this notebook

1. Updating existing values of NumPy array elements
2. Append new elements to a NumPy array using np.append()
3. Insert new elements in a NumPy array using np.insert()
4. Delete elements of a NumPy array using np.delete()
5. Alias vs Shallow Copy vs Deep Copy

In [2]:
# To install this library in Jupyter notebook
#import sys
#!{sys.executable} -m pip install numpy

In [3]:
import numpy as np
np.__version__, np.__path__

('1.24.3', ['C:\\Users\\FashN\\anaconda3\\Lib\\site-packages\\numpy'])

## 1. Updating Existing Values of Numpy Array Elements

### a. 1-D Arrays

In [5]:
arr = np.random.randint(low=1, high=100, size=(10))
print(f'Original array = {arr}')
arr[2] = 460
arr[-1] = 54
print(f'Updated array = {arr}')


Original array = [47 70 66 55 26 28 23 63 47 12]
Updated array = [ 47  70 460  55  26  28  23  63  47  54]


### b. 2-D Arrays

In [10]:
arr = np.random.randint(low=10, high=100, size=(4,4))
print(f'Original array = \n{arr}')
arr[2] = [460, 32,0,-3]
arr[-1][-1] = 54
print(f'Updated array = \n{arr}')

Original array = 
[[21 80 34 98]
 [48 48 96 73]
 [15 93 17 23]
 [96 37 65 14]]
Updated array = 
[[ 21  80  34  98]
 [ 48  48  96  73]
 [460  32   0  -3]
 [ 96  37  65  54]]


## 2. Append New Elements to Numpy Arrays
- The `np.append()` method allows us to insert new values at the end of a NumPy array.
- The method always returns a copy of the existing numpy array with the values appended to the given axis.
```
np.append(arr, values, axis=None)
```
- Where,
    - `arr` is the array in which we want to append
    - `values` must be of the correct shape (the same shape as `arr` excluding `axis`)
    - If `axis` is not specified, both `arr` and `values` are flattened before use.
    - If `axis` is specified, then `values` must be of the correct shape (the same shape as `arr` excluding `axis`)
- The original array remains as such, as it does not occur in-place.

### a. Appending Elements in 1-D Arrays

In [15]:
arr1 = np.random.randint(low=11, high=100, size=10)

# You can add a scalar value or a list of values at the end of a 1-D array
arr2 = np.append(arr1, [21,22,23,24])

print(f'Array1 = {arr1}\nAfter appending\nArray1 = {arr1}\nArray2 = {arr2}\n\nid(arr1) = {id(arr1)}\nid(arr2) = {id(arr2)}')

Array1 = [17 83 79 49 76 73 94 20 64 23]
After appending
Array1 = [17 83 79 49 76 73 94 20 64 23]
Array2 = [17 83 79 49 76 73 94 20 64 23 21 22 23 24]

id(arr1) = 2207412665776
id(arr2) = 2207414805840


### b. Appending Elements in 2-D Arrays

**Example:** In case of 2-D Arrays if `axis` is not mentioned both `arr` and `values` are flattened before use

In [18]:
arr1 = np.random.randint(low=1, high=30, size=(3,3))
# If the axis is not mentioned, values can be of any shape and both `arr` and `values` are flattened before use.
arr2 = np.append(arr1, [101,105,20,300,333])

print(f'Array1 = {arr1}\n\nAfter appending:\nArray1 = \n{arr1}\nArray2 = \n{arr2}\n\nid(arr1) = {id(arr1)}\nid(arr2) = {id(arr2)}')

Array1 = [[17 28  8]
 [27 28 26]
 [17 15 27]]

After appending:
Array1 = 
[[17 28  8]
 [27 28 26]
 [17 15 27]]
Array2 = 
[ 17  28   8  27  28  26  17  15  27 101 105  20 300 333]

id(arr1) = 2207415110800
id(arr2) = 2207415110608


**Example:** Appending a Row to a 2-D array (`axis=0`)

In [23]:
arr1 = np.random.randint(low=1, high=30, size=(3,3))
# For appending at axis 0, the values argument must the same shape as `arr` excluding `axis`
# so the values should be a row vector, and in this case of shape (1,3), having 1 row and 3 columnsarr2 = np.append(arr1, [101,105,20,300,333])

arr2 = np.append(arr1, [[101,202,303]], axis=0)
print(f'Array1 = \n{arr1}\narr1.shape = {arr1.shape}\n\n\nAfter appending:\nArray1 = \n{arr1}\narr1.shape = {arr1.shape}\n\nArray2 = \n{arr2}\narr2.shape = {arr2.shape}\n\n\nid(arr1) = {id(arr1)}\nid(arr2) = {id(arr2)}')

Array1 = 
[[26 26  2]
 [ 1 12 21]
 [22 21 11]]
arr1.shape = (3, 3)


After appending:
Array1 = 
[[26 26  2]
 [ 1 12 21]
 [22 21 11]]
arr1.shape = (3, 3)

Array2 = 
[[ 26  26   2]
 [  1  12  21]
 [ 22  21  11]
 [101 202 303]]
arr2.shape = (4, 3)


id(arr1) = 2207426785712
id(arr2) = 2207426784560


**Example:** Appending a Column to a 2-D array (`axis=1`)

In [29]:
arr1 = np.random.randint(low=10, high=300, size=(3,4))
# For appending at axis 1, the values argument must the same shape as `arr` excluding `axis`
# so the values should be a column vector of shape (4,1), having 4 rows and 1 column

arr2 = np.append(arr1, [[101],[202],[303]], axis=1)
print(f'Array1 = \n{arr1}\narr1.shape = {arr1.shape}\n\n\nAfter appending:\nArray1 = \n{arr1}\narr1.shape = {arr1.shape}\n\nArray2 = \n{arr2}\narr2.shape = {arr2.shape}\n\n\nid(arr1) = {id(arr1)}\nid(arr2) = {id(arr2)}')

Array1 = 
[[169 203  42 131]
 [180 255 138 145]
 [139 241 111  18]]
arr1.shape = (3, 4)


After appending:
Array1 = 
[[169 203  42 131]
 [180 255 138 145]
 [139 241 111  18]]
arr1.shape = (3, 4)

Array2 = 
[[169 203  42 131 101]
 [180 255 138 145 202]
 [139 241 111  18 303]]
arr2.shape = (3, 5)


id(arr1) = 2207428516848
id(arr2) = 2207428510704


## 3. Inserting New Elements in Numpy Arrays
- The `np.insert()` method allows us to insert new values along the given axis before the given index.
- The method always returns a copy of the existing numpy array with the values inserted to the given axis.
```
np.insert(arr, index, values, axis=None)
```
- Where,
    - `arr` is the array in which we want to insert
    - `index` is the index before which we want to insert
    - `values` [array_like] values to be added in the `arr`
    - If `axis` is not specified, both `arr` and `values` are flattened before use.
    - If `axis` is zero, a row is inserted (For 2-D arrays)
    - If `axis` is one, a column is inserted (For 2-D arrays)
- The original array remains as such, as it does not occur in-place.

### a. Inserting Elements in 1-D Arrays

In [30]:
arr1 = np.random.randint(low=4, high=16, size=5)
# You can insert a scalar value or a list of values in between array elements before the mentioned index
arr2 = np.insert(arr1, 3, [55,33,44])
print(f'Array1 = \n{arr1}\nAfter insert:\narr1 = {arr1}\narr2={arr2}')

Array1 = 
[ 8  9  4  7 13]
After insert:
arr1 = [ 8  9  4  7 13]
arr2=[ 8  9  4 55 33 44  7 13]


### b. Inserting Elements in 2-D Arrays


**Example:** In case of 2-D array, if `axis` is not mentioned the array is flattened first

In [31]:
arr1 = np.random.randint(low=4, high=16, size=(4,3))
# You can insert a scalar value or a list of values in between array elements before the mentioned index
arr2 = np.insert(arr1, 4, 1001)
print(f'Array1 = \n{arr1}\nAfter insert:\narr1 = {arr1}\narr2={arr2}')

Array1 = 
[[15 15 12]
 [14 13 14]
 [14  9 11]
 [15 12 11]]
After insert:
arr1 = [[15 15 12]
 [14 13 14]
 [14  9 11]
 [15 12 11]]
arr2=[  15   15   12   14 1001   13   14   14    9   11   15   12   11]


In [32]:
arr2 = np.insert(arr1, 4, [1001, 2002])
print(f'Array1 = \n{arr1}\nAfter insert:\narr1 = {arr1}\narr2={arr2}')

Array1 = 
[[15 15 12]
 [14 13 14]
 [14  9 11]
 [15 12 11]]
After insert:
arr1 = [[15 15 12]
 [14 13 14]
 [14  9 11]
 [15 12 11]]
arr2=[  15   15   12   14 1001 2002   13   14   14    9   11   15   12   11]


**Example:** If axis=0, value(s) are added as a row before mentioned index

In [35]:
arr1 = np.random.randint(low=4, high=16, size=(4,3))
# You can insert a scalar value or a list of values in between array elements before the mentioned index
arr2 = np.insert(arr1, 3, 1001, axis=0)
print(f'Array1 = \n{arr1}\nAfter insert:\narr1 = \n{arr1}\narr2=\n{arr2}')

Array1 = 
[[ 5  6  7]
 [ 7 11  9]
 [ 9  4  8]
 [13  8  6]]
After insert:
arr1 = 
[[ 5  6  7]
 [ 7 11  9]
 [ 9  4  8]
 [13  8  6]]
arr2=
[[   5    6    7]
 [   7   11    9]
 [   9    4    8]
 [1001 1001 1001]
 [  13    8    6]]


In [37]:
# For axis=0, note the size of values has to be 4 in this case (equal to number of columns)
arr2 = np.insert(arr1, 2, [31,34,36], axis=0)
print(f'Array1 = \n{arr1}\nAfter insert:\narr1 = \n{arr1}\narr2=\n{arr2}')

Array1 = 
[[ 5  6  7]
 [ 7 11  9]
 [ 9  4  8]
 [13  8  6]]
After insert:
arr1 = 
[[ 5  6  7]
 [ 7 11  9]
 [ 9  4  8]
 [13  8  6]]
arr2=
[[ 5  6  7]
 [ 7 11  9]
 [31 34 36]
 [ 9  4  8]
 [13  8  6]]


**Example:** If axis=1, value(s) are added as a column at mentioned index

In [38]:
arr1 = np.random.randint(low=4, high=16, size=(4,3))
# You can insert a scalar value or a list of values in between array elements before the mentioned index
arr2 = np.insert(arr1, 3, 1001, axis=1)
print(f'Array1 = \n{arr1}\nAfter insert:\narr1 = \n{arr1}\narr2=\n{arr2}')

Array1 = 
[[11  7 14]
 [12  5 12]
 [11 15 14]
 [ 4 13 14]]
After insert:
arr1 = 
[[11  7 14]
 [12  5 12]
 [11 15 14]
 [ 4 13 14]]
arr2=
[[  11    7   14 1001]
 [  12    5   12 1001]
 [  11   15   14 1001]
 [   4   13   14 1001]]


In [40]:
# For axis=0, note the size of values has to be 4 in this case (equal to number of columns)
arr2 = np.insert(arr1, 2, [31,34,36, 45], axis=1)
print(f'Array1 = \n{arr1}\nAfter insert:\narr1 = \n{arr1}\narr2=\n{arr2}')

Array1 = 
[[11  7 14]
 [12  5 12]
 [11 15 14]
 [ 4 13 14]]
After insert:
arr1 = 
[[11  7 14]
 [12  5 12]
 [11 15 14]
 [ 4 13 14]]
arr2=
[[11  7 31 14]
 [12  5 34 12]
 [11 15 36 14]
 [ 4 13 45 14]]


## 4. Deleting  Elements of Numpy Arrays
- The `np.delete()` method allows us to delete value(s) from an array at the given index
- This function always returns a copy of the existing numpy array with the values deleted from the given axis.
- If axis is not specified, values can be of any shape and will be flattened before use
```
np.delete(arr, index, axis=None)
```
- The original array remains as such, as it does not occur in-place.

### a. Deleting Elements from a 1-D Arrays
**Example:**

In [45]:
arr1 = np.random.randint(low=4, high=16, size=5)
# You can delete a scalar value from a specific index
arr2 = np.delete(arr1, 3)
print(f'Array1 = \n{arr1}\nAfter delete:\narr1 = \n{arr1}\narr2=\n{arr2}')

Array1 = 
[11 14 12 14 13]
After insert:
arr1 = 
[11 14 12 14 13]
arr2=
[11 14 12 13]


In [46]:
arr1 = np.random.randint(low=4, high=16, size=10)
# You can delete a scalar value from a specific index
arr2 = np.delete(arr1, [2,7])
print(f'Array1 = \n{arr1}\nAfter delete:\narr1 = \n{arr1}\narr2=\n{arr2}')

Array1 = 
[13  7  5  5  7  7  8 15 13 12]
After delete:
arr1 = 
[13  7  5  5  7  7  8 15 13 12]
arr2=
[13  7  5  7  7  8 13 12]


### b. Deleting Elements from a 2-D Arrays

**Example:** Delete a specific element from a 2-D array, don't mention the axis. The resulting array is flattened before use

In [47]:
arr1 = np.random.randint(low=4, high=16, size=(3,3))
# You can delete a scalar value from a specific index
arr2 = np.delete(arr1, 5)
print(f'Array1 = \n{arr1}\nAfter delete:\narr1 = \n{arr1}\narr2=\n{arr2}')

Array1 = 
[[14  5  9]
 [11  9 12]
 [11  4 11]]
After delete:
arr1 = 
[[14  5  9]
 [11  9 12]
 [11  4 11]]
arr2=
[14  5  9 11  9 11  4 11]


**Example:**  Delete a specific row from an existing 2-D array

In [48]:
arr1 = np.random.randint(low=4, high=16, size=(4,4))
arr2 = np.delete(arr1, 2,axis=0)
print(f'Array1 = \n{arr1}\nAfter delete:\narr1 = \n{arr1}\narr2=\n{arr2}')

Array1 = 
[[14 13  4 11]
 [ 5  8  6  7]
 [ 5  9 14  6]
 [ 9 12 15 14]]
After delete:
arr1 = 
[[14 13  4 11]
 [ 5  8  6  7]
 [ 5  9 14  6]
 [ 9 12 15 14]]
arr2=
[[14 13  4 11]
 [ 5  8  6  7]
 [ 9 12 15 14]]


**Example:**  Delete a specific column from an existing 2-D array

In [49]:
arr1 = np.random.randint(low=4, high=16, size=(4,4))
arr2 = np.delete(arr1, 2,axis=1)
print(f'Array1 = \n{arr1}\nAfter delete:\narr1 = \n{arr1}\narr2=\n{arr2}')

Array1 = 
[[12 10 14 13]
 [14  9 10 12]
 [ 6  4  8  6]
 [ 6 11  4  8]]
After delete:
arr1 = 
[[12 10 14 13]
 [14  9 10 12]
 [ 6  4  8  6]
 [ 6 11  4  8]]
arr2=
[[12 10 13]
 [14  9 12]
 [ 6  4  6]
 [ 6 11  8]]


## 5. Assigning vs Coping NumPy Arrays

### a. Assigning two NumPy Arrays (Create an alias)

In [53]:
arr1 = np.random.randint(low=4, high=16, size=10)
# Creating a copy using assignment operator, both variables point at the same array

arr2 = arr1
print(f'Array1 = \n{arr1}\nAfter copying:\nArray2=\n{arr2}\n{id(arr1)}\n{id(arr2)}')

Array1 = 
[ 4 13 11  5  6 10  5 13 14 13]
After copying:
Array2=
[ 4 13 11  5  6 10  5 13 14 13]
2207428671408
2207428671408


### b. View/Shallow Copy
Arrays that share some data. The view method creates an object looking at the same data. Slicing an array returns a view of that array.

In [57]:
arr1 = np.random.randint(low = 1, high = 10, size = 10)
# Creating a shallow copy (view) using slice operator
arr2 = arr1[:]

# Change value in arr1 will occur in arr2
arr2[8] = 40
print(f'arr1 = {arr1}\narr2 = {arr2}\n{id(arr1)}\n{id(arr2)}\n\nAfter change\narr2 = {arr2}')

arr1 = [ 7  3  2  3  3  4  2  6 40  2]
arr2 = [ 7  3  2  3  3  4  2  6 40  2]
2207428657488
2207428666416

After change
arr2 = [ 7  3  2  3  3  4  2  6 40  2]


### c. Deep Copy

In [59]:
arr1 = np.random.randint(low = 1, high = 10, size = 10)
# Create a Deep copy using copy() method, which will create a new copy of the array

arr2 = arr1.copy()
arr2[8] = 40
print(f'arr1 = {arr1}\narr2 = {arr2}\n{id(arr1)}\n{id(arr2)}\n\nAfter change\narr2 = {arr2}')

arr1 = [6 4 7 2 3 4 1 3 2 2]
arr2 = [ 6  4  7  2  3  4  1  3 40  2]
2207428327248
2207428670064

After change
arr2 = [ 6  4  7  2  3  4  1  3 40  2]
